### ISSUE TITLE
Letras del logo desbordadas

### ISSUE THREAD

**Issue by jhonarlem** [midudev/aprende-javascript-problemas#100]
Las letras del logo se encuentran desbordadas, gran trabajo midudev 😁

**Comment by midudev** [comment]
jajaja buen trabajo por desbordar las letras? 🤣

**Comment by midudev** [comment]
He cambiado el logo por el oficial de JavaScript

**Comment by jhonarlem** [comment]
> jajaja buen trabajo por desbordar las letras? rofl

No no no no, hablo de todo tu trabajo en general, saludos desde 🇨🇴
