### ISSUE TITLE
Operadores lógicos en JavaScript: segundo ejercicio

### ISSUE THREAD

**Issue by FernandoCM18** [midudev/aprende-javascript-problemas#102]
El segundo ejercicio: 
Tenemos un producto en una tienda. Cuesta 1500 y tenemos un descuento del 25%. Tengo 1150€ en mi cartera. Escribe un código que me diga si puedo comprarlo. No uses paréntesis.

Me da respuesta incorrecta la siguiente:
1500 >= 1500 - 1500 * 0.25 

Pero en consola es correcto:

<img width="233" alt="Captura de Pantalla 2023-04-20 a la(s) 11 41 53 a m" src="https://user-images.githubusercontent.com/35951365/233458616-e32ebcf0-d567-47a3-99a0-06ac206da048.png">

**Comment by Gianni03** [comment]
tambien da error el primer ejercicio si haces 7>8 && 7<10, solo lo da correcto con los espacios 7 > 8 && 7 < 10
