### ISSUE TITLE
En landscape los logros se solapan.


### ISSUE THREAD

**Issue by BingenWeb** [midudev/aprende-javascript-problemas#104]
![Screenshot_20230420-205004_Chrome.jpg](https://user-images.githubusercontent.com/126512014/233460395-0bee189d-15c6-403a-ae22-0ee8ab337298.jpg)

**Comment by midudev** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/1561955/233474837-ceef1d7c-537f-4f6a-aef4-9e49f4dd60ac.png">

Ahora salen en una columna.
