### ISSUE TITLE
Crear boton para volver al menú principal

### ISSUE THREAD

**Issue by BingenWeb** [midudev/aprende-javascript-problemas#105]
![Screenshot_20230420-210900_Chrome.jpg](https://user-images.githubusercontent.com/126512014/233464056-3d5e7366-a61c-4ace-9213-dee8c035c733.jpg)

**Comment by midudev** [comment]
Hemos mejorado la navegación en móvil para que puedas volver a cualquier sitio. :)

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1561955/233624173-6f6708dc-33f0-4feb-b699-71599e2bd8e9.png">
