### ISSUE TITLE
Mejora visual icono JS Beta

### ISSUE THREAD

**Issue by devAlbertodc** [midudev/aprende-javascript-problemas#108]
En pantallas con grandes dimensiones, al acceder a logros, para volver al menú principal hay que cruzar toda la pantalla.
Para ser más accesible podría ubicarse en la barra lateral derecha

![img_main_screen](https://user-images.githubusercontent.com/39799309/233469295-e7be070f-89d7-453a-8035-a7f071f928a3.PNG)

**Comment by midudev** [comment]
Hemos añadido el botón de volver atrás, al lado del título.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/1561955/233624103-7814d5fb-a5dd-4e3f-8bc1-bad9899a1d12.png">
