### ISSUE TITLE
Distintas formas de solución

### ISSUE THREAD

**Issue by HacheGe60** [midudev/aprende-javascript-problemas#109]
![Posible error](https://user-images.githubusercontent.com/114962185/233470479-2c3b3b6b-671d-4cb9-bde0-dc6798c349ed.png)

**Comment by HacheGe60** [comment]
También da error si uno pone .75 en lugar de 0.75

**Comment by cjodra** [comment]
O al revés
![mal](https://user-images.githubusercontent.com/58395291/233493422-4a1bbd31-85c0-4932-b450-0d4b95dde71a.JPG)

**Comment by midudev** [comment]
Repetido:
https://github.com/midudev/aprende-javascript-problemas/issues/102

**Comment by caramza** [comment]
Lo exprese así y tambien me sale error, pero en consola me sale true:

1500 - 1500 * 25 / 100 <= 1150
