### ISSUE TITLE
Avatar Fix

### ISSUE THREAD

**Issue by sebastianterleira** [midudev/aprende-javascript-problemas#11]
![image](https://user-images.githubusercontent.com/108709097/233428936-40aba82a-2656-4c19-9ba7-fa9a10a6d8de.png)
![image](https://user-images.githubusercontent.com/108709097/233428973-497d9408-39a5-4699-b914-9926448d1d72.png)

**Comment by sebastianterleira** [comment]
Funciona con inico de Google pero con github esta broken

**Comment by midudev** [comment]
Creo que esto lo hemos arreglado ya.
