### ISSUE TITLE
bug logo en modo movil

### ISSUE THREAD

**Issue by lorenzo-mm** [midudev/aprende-javascript-problemas#110]
el logo se pone por de bajo del texto del temporizador en modo movil.

![4cd1a095-22c7-4f7f-aee6-f924e927870d](https://user-images.githubusercontent.com/94995682/233471653-c0ebcfae-55fe-4e3d-98a3-aaa343019043.jpg)

**Comment by midudev** [comment]
Hemos arreglado el modo móvil.
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1561955/233622621-c8c27cff-d215-4e69-8eaa-cf1085013796.png">
