### ISSUE TITLE
Resultados incorrecto

### ISSUE THREAD

**Issue by jmrona** [midudev/aprende-javascript-problemas#112]
![Screenshot_2023-04-20-21-05-03-034_com android chrome](https://user-images.githubusercontent.com/32115263/233476149-1f5ae879-ab62-4221-844f-3f7e29dd01c9.jpg)

Si no dejo espacio entre los números y operadores me sale que la respuesta es incorrecta pero si pongo espacio entonces si sale que es correcta. Además el mensaje de respuesta correcta o incorrecta sale del container.

**Comment by jmrona** [comment]
Además en móvil no encuentro como volver a la página principal

**Comment by midudev** [comment]
Repetido.
