### ISSUE TITLE
Fecha errada al finalizar logro

### ISSUE THREAD

**Issue by Sthephany04** [midudev/aprende-javascript-problemas#118]
Finalice la primera sección el 20 de abril (jueves) a las 19:20 pero lo marca como finalizado el 21 de abril. 
![Captura de Pantalla 2023-04-20 a la(s) 7 22 59 p m](https://user-images.githubusercontent.com/61255223/233512994-edadcd8d-8151-44c1-9483-d72bfb57e89b.jpg)

**Comment by soyluisarrieta** [comment]
En mi caso si la marcó correctamente:
![image](https://user-images.githubusercontent.com/88900534/233517252-5961a779-a28e-4294-8953-39bee500192e.png)

La razón es sencilla, la **zona horaria del servidor** es diferente a la tuya, lo que significa que justo cuando hiciste tu lección, ya era 21 de abril en España.

**Comment by RafaMojica** [comment]
Me imagino que el programa esta echo en la zona horaria de españa por lo que depende de la hora que realices los ejercicios es un dia u otro

**Comment by midudev** [comment]
Creo que era un error que había en el sistema de logros que se volvía a enviar al terminar cada sección.
