### ISSUE TITLE
Posible error en el texto de "Variables var"

### ISSUE THREAD

**Issue by VictorSosa-dev** [midudev/aprende-javascript-problemas#120]
En este texto no se si querías escribir la diferencia entre "let y const" en lugar de decir "let y var"

![Screenshot 2023-04-20 at 20 28 13](https://user-images.githubusercontent.com/73664479/233526283-7bfdca81-c806-473e-9f82-2010d8121b20.png)

**Comment by midudev** [comment]
Está bien el texto. :) Pero he añadido también const, para que quede claro que hablaremos de las diferencias de las tres.
