### ISSUE TITLE
Fallo UX - Vista de Logros no tiene un botón de regreso

### ISSUE THREAD

**Issue by Dario-Elguero** [midudev/aprende-javascript-problemas#122]
Cuando uno entra a ver los logros no tiene un botón volver, por lo que en la experiencia de usuario te deja un poco diciendo y como salgo de acá, obviamente podes utilizar el volver del navegador pero no seria tan correcto.

**Comment by midudev** [comment]
Ahora al lado del título tienes el botón de volver atrás:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/1561955/233625998-1fd07263-9f09-41e2-9fa1-3a0f6e074ff9.png">
