### ISSUE TITLE
Error al reproducir en Microsoft Edge. 

### ISSUE THREAD

**Issue by DruckDeveloper** [midudev/aprende-javascript-problemas#123]
## Error: 
Al intentar reproducir una lección, el contenido no carga utilizando el navegador **Microsoft Edge**

## Captura de pantalla del error:
![image](https://user-images.githubusercontent.com/91342470/233557374-25ffb478-eaea-4dae-ba64-186f3c134891.png)

**Comment by midudev** [comment]
Lo estamos mirando ya, ya tenemos la issue. Gracias!
