### ISSUE TITLE
(sugerencia, posible error a futuro) comprobar solución en los ejercicios interactivos funciona raro

### ISSUE THREAD

**Issue by AdriVazquez** [midudev/aprende-javascript-problemas#124]
En los ejercicios de código interactivo, al poner como solución 10 >= 9 lo da por válido, 10=>9 también, pero 10 >=9 y 10=> 9 no. Nótese que únicamente hay espacio en uno de los dos lados del comparador. En este ejemplo no es importante, pero en el futuro, puede pasar que en casos más complejos, el validador no funcione y el alumno se vuelva loco.

**Comment by midudev** [comment]
Repe: https://github.com/midudev/aprende-javascript-problemas/issues/48
