### ISSUE TITLE
Revisen issue #78

### ISSUE THREAD

**Issue by JMDTol** [midudev/aprende-javascript-problemas#125]
Ver mi comentario del final, a cada cuenta le asigna un nombre y una imagen con el mismo mail.

https://github.com/midudev/aprende-javascript-problemas/issues/78

**Comment by midudev** [comment]
Sí, según esta issue, mientras el email sea exactamente el mismo, hace un linking del usuario: https://github.com/orgs/supabase/discussions/3098

**Comment by JMDTol** [comment]
En las capturas os muestro mi mail, es exactamente el mismo, no hay trampa ni cartón (pero obviamente tengo que tapar parte, no tengo problema en remitírtelo a tu mail), y como puedes ver en las capturas que he dejado en el issue #78 aparecen nombres y fotos diferentes. Supongo que el problema es de supabase, pero al menos que estéis informados por si no es así.
