### ISSUE TITLE
[UI] border-radius de la parte inferior del menú de Cerrar Sesión

### ISSUE THREAD

**Issue by bonavida** [midudev/aprende-javascript-problemas#126]
Al hacer hover sobre "Cerrar Sesión", se pierde el `border-radius` de la parte inferior del menú.

![Captura de pantalla 2023-04-21 a las 11 11 56](https://user-images.githubusercontent.com/8061481/233599070-9cb8d95c-da08-4782-8004-f9745a8d7ea4.png)

**Comment by midudev** [comment]
Fixed.
