### ISSUE TITLE
Idea: Mover el banner de compartir Twitter por que se superpone con los toast

### ISSUE THREAD

**Issue by jonathanfernandezfm** [midudev/aprende-javascript-problemas#127]
Las notifications toast aparecen sobre el banner y queda algo raro a la vista

**Comment by tonyjleal** [comment]
Podrías poner el banner de compartir en twitter en la columnas de iconos del usuario, debajo de avisar de un error, o al lado del avatar. Es bastante intrusivo el que aparece.

**Comment by Jinder2050** [comment]
Se refieren a esto?
![image](https://user-images.githubusercontent.com/76700460/233744684-c8852da2-f96d-455d-8d5c-e0175e9a3fe6.png)

**Comment by midudev** [comment]
En móvil hemos hecho que ocupe menos espacio y lo del toast queda por encima, tampoco parece muy grave.
