### ISSUE TITLE
Sugerencia: Debería haber un botón para volver a la pantalla de inicio cuando acabamos las secciones y no hay mas a continuación

### ISSUE THREAD

**Issue by jonathanfernandezfm** [midudev/aprende-javascript-problemas#128]
La idea es evitar tener que ir al logo hasta arriba a la izquierda, y seguir el mismo flow de pasar de sección, pero dado que no hay mas, se redirige a la pagina de inicio que tiene la vista general.

Otra idea seria poner tambien un boton de continuar, disabled y con un contador hasta el proximo desbloqueo de sección.

![image](https://user-images.githubusercontent.com/33097447/233617861-00ee6da2-3119-4491-b4c7-4c736a3c0565.png)

**Comment by midudev** [comment]
Añadido.
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1561955/233658782-1a7902cf-5b53-40b7-92b6-755d19cf58f5.png">
