### ISSUE TITLE
Timeout de aplicación no devuelve a la home, da error de "client-side exception"

### ISSUE THREAD

**Issue by matiasbaldanza** [midudev/aprende-javascript-problemas#130]
Esto está probablemente relacionado con el issue #16, cerrado ayer.

Como comenté en ese mismo issue, luego de unas horas, al volver a la pestaña abierta del curso me encontré con el mismo error de client-side exception. Un refresh manual me devolvió a la página principal del curso pero con la sesión iniciada normalmente (por lo que no sé si era un timeout.)

Nota adicional: en dark mode, el texto del error es ilegible a menos que lo seleccione, que es lo que se ve en pantalla.

No creo que sea un error severo, pero sí queda feíllo como UX. 

✌️😁

![Screen Shot 2023-04-21 at 08 14 41](https://user-images.githubusercontent.com/55600/233623841-66e8242d-0d09-4340-ac00-de6518414e58.png)

**Comment by midudev** [comment]
Está difícil de ver cuál puede ser el problema. Estoy investigando a ver. Cualquier idea es bienvenida. Queda claro que es por algo de la sesión tras pasar un tiempo pero es jodido replicar.
