### ISSUE TITLE
Operadores Logicos

### ISSUE THREAD

**Issue by Gabriel-Aguero** [midudev/aprende-javascript-problemas#135]
Si no me equivoco el 25% corresponde al 0.25 y en la respuesta pusiste 0.75 que seria el 75% midu. El curso esta genial te felicito por lo que haces. Sos un Crack !!! Saludos desde Argentina y te esperamos !!!!

 #132

**Comment by midudev** [comment]
Tener un descuento del 25% significa que es el 0.75 del precio. :)
