### ISSUE TITLE
Subtitulado Captioner CC

### ISSUE THREAD

**Issue by emiliogril** [midudev/aprende-javascript-problemas#136]
Hola querido, como estas? Te cuento soy hipoacúsico desde Argentina (Buenos Aires). El año pasado inicie una carrera "Desarrollo Full Stack" en coderHouse. Por suerte me recibi con muchos esfuerzo desde diciembre 2022.
Como lo hice en los cursos en distancia Virtuales para entender en las clases? Cuento con la aplicación que se llama "Web Captioner" (https://webcaptioner.com/) que permite traducir de audio a texto. Eso lo hacia yo que me ayudo un montón.

El motivo es que me gustaria en los videos tuyos desde twitch que cuente algo "CC" captioner para poder leer en vivo y tambien en los cursos que salga la opcion subtitulador si es posible hacer buenisimo.
Sino la otra opcion es seguir usando el webCaptioner.

Desde ya muchas gracias por leerme y te admiro mucho lo que haces.

Un abrazo fuerte

Emi
Te dejo mi link cuando empeze en el primer curso y vealo tu mismo para que me conozcas:
https://www.linkedin.com/posts/emilio-gril_motivaciaejn-reactjs-inclusionlaboral-activity-6925269243022184448-H55t?utm_source=share&utm_medium=member_desktop

**Comment by midudev** [comment]
¡Gracias! Por ahora puedes usar Web Captioner y similares mientras ves mis vídeos, para que también lo haga automáticamente.
