### ISSUE TITLE
Dropdown perfil

### ISSUE THREAD

**Issue by aixegorri** [midudev/aprende-javascript-problemas#138]
El nombre de perfil del desplegable en el avatar no tiene el contraste de color correcto.

<img width="204" alt="Captura de pantalla 2023-04-21 a las 15 53 29" src="https://user-images.githubusercontent.com/33580056/233656080-7cb590f5-f449-424a-8a5b-6ebd17e7fee4.png">

**Comment by midudev** [comment]
Arreglado!
