### ISSUE TITLE
Sugerencia: Estilos de la scrollbar mejorada 

### ISSUE THREAD

**Issue by yangenmanuel** [midudev/aprende-javascript-problemas#141]
Sugiero estilos para la scrollbar del sitio para una experiencia mas suave y evitar el contraste entre el suave color de fondo y una scrollbar gris por defecto:

```
body::-webkit-scrollbar {
  background: #13111C;
}

body::-webkit-scrollbar-thumb {
  background-color: #FBBF24;
  border-radius: 20px;
}
```

![Aprende JavaScript - Curso gratis para aprender programación con JavaScript - Brave 21_04_2023 11_40_23](https://user-images.githubusercontent.com/59752868/233666683-47082f9f-d40e-4935-8c4b-a43eaf743958.png)

**Comment by midudev** [comment]
Hecho!
