### ISSUE TITLE
Console error reported

### ISSUE THREAD

**Issue by zettsu** [midudev/aprende-javascript-problemas#142]
Page https://www.aprendejavascript.dev/clase/introduccion/null-y-undefined

```javascript
DevTools failed to load source map: Could not load content for chrome-extension://ljdobmomdgdljniojadhoplhkpialdid/common/browser-polyfill.js.map: Error del sistema: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: Error del sistema: net::ERR_FILE_NOT_FOUND
browser-polyfill.js:588 Uncaught (in promise) {message: 'The message port closed before a response was received.'}message: "The message port closed before a response was received."[[Prototype]]: Object
(anónimas) @ browser-polyfill.js:588
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: Error del sistema: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://ljdobmomdgdljniojadhoplhkpialdid/common/browser-polyfill.js.map: Error del sistema: net::ERR_BLOCKED_BY_CLIENT
browser-polyfill.js:588 Uncaught (in promise) {message: 'The message port closed before a response was received.'}
(anónimas) @ browser-polyfill.js:588
```

**Comment by imjheef** [comment]
> Page https://www.aprendejavascript.dev/clase/introduccion/null-y-undefined
> 
> ```js
> DevTools failed to load source map: Could not load content for chrome-extension://ljdobmomdgdljniojadhoplhkpialdid/common/browser-polyfill.js.map: Error del sistema: net::ERR_BLOCKED_BY_CLIENT
> DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: Error del sistema: net::ERR_FILE_NOT_FOUND
> browser-polyfill.js:588 Uncaught (in promise) {message: 'The message port closed before a response was received.'}message: "The message port closed before a response was received."[[Prototype]]: Object
> (anónimas) @ browser-polyfill.js:588
> DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: Error del sistema: net::ERR_FILE_NOT_FOUND
> DevTools failed to load source map: Could not load content for chrome-extension://ljdobmomdgdljniojadhoplhkpialdid/common/browser-polyfill.js.map: Error del sistema: net::ERR_BLOCKED_BY_CLIENT
> browser-polyfill.js:588 Uncaught (in promise) {message: 'The message port closed before a response was received.'}
> (anónimas) @ browser-polyfill.js:588
> ```

¿Puedes verificar que no tengas un AdBlocker activado? Trate de reproducir el error pero no me sale nada a mi.

**Comment by zettsu** [comment]
Verifique cada una de las extensiones y el error se da en particular con
Katalon Recorder

**Comment by midudev** [comment]
El error no es de la web, es de la extensión. Cierro esto.
