### ISSUE TITLE
LOGO TWITTER

### ISSUE THREAD

**Issue by SaulDevjr** [midudev/aprende-javascript-problemas#145]
Parece que el logo de twitter incomoda al momento de de clikar en la ventana de video por lo menos para expandir y tambien para ver los 3 puntos
![logotwt](https://user-images.githubusercontent.com/100041319/233691052-052ae34e-3f4f-476a-aec4-4ce95e776c70.jpg)

**Comment by Jinder2050** [comment]
> Parece que el logo de twitter incomoda al momento de de clikar en la ventana de video por lo menos para expandir y tambien para ver los 3 puntos ![logotwt](https://user-images.githubusercontent.com/100041319/233691052-052ae34e-3f4f-476a-aec4-4ce95e776c70.jpg)


Parece que es por el dispositivo, en que tamaño o tipo de dispositivo estás? Parece que le aumentaste zoom o.o


![image](https://user-images.githubusercontent.com/76700460/233745865-56d317a3-2896-40ab-b145-5bfc3d3ba4a8.png)

**Comment by SaulDevjr** [comment]
[image: image.png]
Es un notebook lenovo ideapad modelo viejo 310 con window 11 mi zoom parece
estar al 100% y aun asi esta de esa manera, quizas algun error en mi
configuracion visual voy a chequear

**Comment by SaulDevjr** [comment]
windows 10pro sorry

**Comment by midudev** [comment]
¿Pero no puedes hacer un poco más de scroll para poder darle?
