### ISSUE TITLE
Posibilidad de usar la tecla 'Enter' para enviar respuesta

### ISSUE THREAD

**Issue by Rubxnb** [midudev/aprende-javascript-problemas#152]
No es un bug o error. 
Simplemente cuando he escrito la línea de código de algún ejercicio, inconscientemente he pulsado la tecla 'Enter' para enviar la respuesta.
Entiendo que posiblemente esto de problemas en ejercicios posteriores en los que se deban de crear más de una línea de código, pero dejo mi observación o propuesta de mejora.

**Comment by midudev** [comment]
Ya lo enviaron en otro sitio, vamos a hacerlo. :)
