### ISSUE TITLE
Github issues

### ISSUE THREAD

**Issue by ghost** [midudev/aprende-javascript-problemas#153]
Cuando se ingresa a comentar el error en el botón reportar se dirige al enlace de github pero al ir hacia atrás vuelve a github de nuevo, sería ideal que la abriera en otra pestaña esto me sucede en safari iPhone

**Comment by midudev** [comment]
No entiendo muy bien el problema, pero no parece que podamos hacer nada en la plataforma, que ya tiene un target=_blank.

**Comment by ghost** [comment]
Cuando se ingresa a comentar el error en el botón reportar se dirige al enlace de github pero al ir hacia atrás vuelve a github de nuevo, sería ideal que la abriera en otra pestaña esto me sucede en safari iPhone
