### ISSUE TITLE
Aclaraciones sobre tipos de datos

### ISSUE THREAD

**Issue by omgslinux** [midudev/aprende-javascript-problemas#155]
En general, y al ser la temática explicar los distintos tipos obtenidos con <code>typeof</code>, se podían unificar los distintos epígrafes suguiendo el mismo criterio, poniendo, por ejemplo, la nomenclatura <code>Números ("number")</code>. Aquí cabe destacar que se introduce una confusión en "Cadenas de texto (strings)" por usar el plural, además de justamente debajo ponerlo con mayúscula <code>String</code>. Al usar un ejemplo real de código con este tipo de dato, ninguno de los dos mencionados es correcto. Adicionalmente, en este mismo párrafo, la redacción podría mejorarse, además de unificarse en la definición, donde propongo algo así como <code>Las cadenas de texto (tipo "string"), son otro tipo de datos muy común.</code>
Como sugerencia para mejorar el texto sobre los tipos boolean, hace falta aclarar varias cosas:
- En la primera explicación, aclarar cuál es el verdadero y cuál es el falso, aunque pueda parecer obvio.
- Si es o puede ser "True", "TRUE", etc, así como si son iguales entre ellos ("true" === "True", etc)

**Comment by midudev** [comment]
Fixed
