### ISSUE TITLE
Votacion

### ISSUE THREAD

**Issue by agussantos023** [midudev/aprende-javascript-problemas#156]
No es una opinión es mas una sugerencia ,estaría bien que junto a las notificaciones de las notificaciones hubiera un botón de like o dislike para poder informarte si a la gente le a gustado la actualización o no

**Comment by midudev** [comment]
Sólo me faltaba tener que aguantar que a alguien no le gusten las actualizaciones de un curso gratuito. 😆

**Comment by agussantos023** [comment]
también es verdad ,pero yo no en que yo estoy encantando con el curso
