### ISSUE TITLE
Clases completadas entre inicios de sesión

### ISSUE THREAD

**Issue by devAlbertodc** [midudev/aprende-javascript-problemas#159]
Como las lecciones las completé iniciando sesión en google, sale bien:
![sesion_iniciada_google](https://user-images.githubusercontent.com/39799309/233964185-698ee76a-e947-4679-a18d-658bf01082a8.png)

Cuando inicio sesion con github, me salen sin completar
![sesion_iniciada_github](https://user-images.githubusercontent.com/39799309/233964269-b06461fb-c27f-40ad-aee6-ec8b0e40ae26.png)

**Comment by midudev** [comment]
Si son dos cuentas diferentes, ¿Dónde está el problema exactamente?

**Comment by jalvarezz13** [comment]
¿Utilizas el mismo correo en ambas cuentas? Quizá se pueda asignar el mismo _userId_ a la persona que inicie sesión con el mismo correo independientemente del _provider_ utilizado.

**Comment by devAlbertodc** [comment]
@midudev @jalvarezz13 tengo distintos correos asociados, quizás ese sea el problema

**Comment by midudev** [comment]
Claro, es imposible que pueda asociar las dos cuentas. Vamos, que es normal, lo ve como cuentas diferentes. Lo cierro. :)
