### ISSUE TITLE
Recién registrado, Al hacer clic en "Logros" da error de client-side-exception

### ISSUE THREAD

**Issue by matiasbaldanza** [midudev/aprende-javascript-problemas#16]
al ingresar a Logros, recién registrado. Página en blanco con este error.

Nota: Aún me muestra el botón de "Iniciar sesión" o sea que no me está dejando iniciar.

Application error: a client-side exception has occurred (see the browser console for more information).
Digest: 3146033764

![Screen Shot 2023-04-20 at 13 31 16](https://user-images.githubusercontent.com/55600/233430222-485848d6-e434-4976-b8c2-c62ada0eab51.png)

**Comment by midudev** [comment]
Lo hemos arreglado y hemos hecho que haga redirect a los usuarios no registrados a la home.

**Comment by matiasbaldanza** [comment]
Excelente, Midu. 

Te comento que recién volví al tab que tenía abierto en el curso con la sesión iniciada (unas 7 horas después). 
Hizo un refresh solo y volvió a mostrar el mismo client-side exception. 

Hice reload y me volvió a mostrar mi sesión ok. 

Voy a dejar abierto el tab y ver si repite lo mismo mañana por la mañana. Puede haber sido que necesitaba un reload de mi parte.

✌️😁
