### ISSUE TITLE
Inicio desde Git

### ISSUE THREAD

**Issue by conancos** [midudev/aprende-javascript-problemas#160]
Hola, enhorabuena por tu curso y muchas gracias!

Al lío: Al entrar con Git, en el formulario para inscribir el user y el password, una vez escrito el user, no te deja poner el password, hay que darle al intro, que te dé el error de que no hay password, y entonces ya te deja entrar al password para escribirlo.

Gracias de nuevo, eres el mejor!

**Comment by midudev** [comment]
Eso es un tema de la interfaz de GitHub y no puedo hacer nada por mi parte.
