### ISSUE TITLE
[ISSUE] Selección de comillas simple o doble

### ISSUE THREAD

**Issue by linuxmobile** [midudev/aprende-javascript-problemas#161]
**Problema: Al utilizar comillas simples, la evaluación queda "desaprobada".**

_Para aquellos que solemos utilizar comillas simples, estaría bueno que se pudiera optar por cualquiera de las comillas._ 

![image](https://user-images.githubusercontent.com/10554636/234080736-24668716-0fb9-4c96-a387-c05a51b99c30.png)

**Comment by linuxmobile** [comment]
Añadiendo también otro error común con las comillas:

**Se pasa como "aprobado" el utilizar la comilla simple y luego la doble.**

![image](https://user-images.githubusercontent.com/10554636/234081293-f37ab67d-c47a-4a9b-b963-45fe72a81f0d.png)

**Comment by Dario-Elguero** [comment]
Hola linuxmobile, es raro que en las dos imágenes tenes el mismo ejemplo como `let mensaje = 'Hola JavaScript"` en una te da **incorrecta** y otra **correcta** - De todas maneras salvo que lo hayan corregido ahora, esta funcionando todo bien, probé con comillas simples y da correcta, con comilla dobles da correcta y como esta el ejemplo en la imagen da incorrecta.

**Comment by linuxmobile** [comment]
> Hola linuxmobile, es raro que en las dos imágenes tenes el mismo ejemplo como `let mensaje = 'Hola JavaScript"` en una te da **incorrecta** y otra **correcta** - De todas maneras salvo que lo hayan corregido ahora, esta funcionando todo bien, probé con comillas simples y da correcta, con comilla dobles da correcta y como esta el ejemplo en la imagen da incorrecta.

_Se me confundieron los screenshots, en la primera solo eran comillas simples*_
