### ISSUE TITLE
Seccion "Examen interactivo" label no ocupa todo el DIV

### ISSUE THREAD

**Issue by pa-ku** [midudev/aprende-javascript-problemas#162]
![label](https://user-images.githubusercontent.com/40728995/234093037-25118681-ca1d-4ae5-a6d7-77d4fffea918.gif)

Es un pequeño detalle nada mas, pero justo me pasaba que apretaba, no cambiaba de estado y me estaba volviendo loco 🤪 al final es eso mismo, el label no ocupa todo el div. Capaz un pointer:cursor tambien estaria bueno, pero ya me estoy poniendo tiquismiquis.

PD: Tremendo trabajo te mandaste!, te amo midu gracias por enseñarme tanto 🥰 sos un referente para mi

**Comment by midudev** [comment]
Arreglado. :)
