### ISSUE TITLE
Los ejercicios de practicas no se pueden hacer

### ISSUE THREAD

**Issue by Cristianpinedo** [midudev/aprende-javascript-problemas#164]
En esta sección los ejercicios de practica no se pueden hacer. por lo tanto no se puede completar la sección.

**Comment by midudev** [comment]
Necesito más información. ¿Qué navegador usas? ¿Puedes hacer un vídeo? ¿Qué error te da?

**Comment by Cristianpinedo** [comment]
Hola Midu, el problema se arregló solo, simplemente salí y entre al rato y ya me dejo hacer los ejercicios, uso Edge, y el error era que no me salia el campo para escribir el Código en los ejercicios. gracias por ese super curso, eres un crack.

**Comment by midudev** [comment]
Gracias!
