### ISSUE TITLE
Error en la segunda pregunta del apartado "Los operadores de comparación"

### ISSUE THREAD

**Issue by PcMant** [midudev/aprende-javascript-problemas#165]
Resulta que en esta parte si pones `0 == 0` lo toma por malo cuando el enunciado pide que 0 sea igual a 0, y lo toma por bueno si se pone como respuesta `0 === 0`, que yo sepa, la expresión de triple igual no significa que sea únicamente igual, sino que ambos sean idénticos, tanto el valor como el tipo de dato. Por eso pienso que `==` debería de ser aceptado como una respuesta correcta.

**Comment by Dario-Elguero** [comment]
Hola PcMant, con respecto a esto yo veo el siguiente punto de vista, lo que se esta enseñando en el capitulo es a usar === como igualdad y !== como desigualdad , por lo que dejar que == te de true podría llevar a confusión.
Si te fijas, mas abajo en el titulo **Comparando valores de diferentes tipos**, nombra los comparadores == y != que van ha ser abordados mas adelante.

**Comment by PcMant** [comment]
Por lo que tengo entendido y lo que tengo aprendido de mis estudios en programación es que == es igualdad y === significa idéntico y como diferencia tiene la característica de que este segundo tiene en cuenta el tipo de dato como mencione anteriormente, esto quiere decir que si hacer un `0 == '0'` este devolverá true porque son iguales, pero, en cambio, si haces un `0 === '0'` este dará false, ya que a pesar de ser en ambos 0 se exige en ese caso que ambos sean numéricos y estás comparando el 0 numérico con un string y no son idénticos, para ser idénticos no quedaría de otra que sea `0 === 0` y el enunciado dice igual yo no veo la palabra idéntico en ninguna parte del enunciado, por ese motivo mi opinión y mi postura sobre el tema. A ver si ahora va a resultar que ni sé el tema y ni siquiera se me puede considerar programador junior.

**Comment by Dario-Elguero** [comment]
Es que yo nunca dije que esta mal lo que decías, te puse el punto de vista de porque da falso el ==. Si ves el enunciado esta enseñando usar === y no == entonces porque va dejar que funciones el == . Claramente como vos ya tener experiencia sabes la diferencia pero alguien que esta aprendiendo le va a llevar a confusión, por eso mas adelante el mismo enunciado dice que se va a explicar como funcionan los operadores débil como == y !=
