### ISSUE TITLE
No se visualiza bien

### ISSUE THREAD

**Issue by HolaJose2** [midudev/aprende-javascript-problemas#166]
Entré a la pagina para ver el curso, y se ve todo blanco.

![image](https://user-images.githubusercontent.com/110427144/234131295-fde9a075-5c49-4b8f-a91b-2d66a3630549.png)

**Comment by Dario-Elguero** [comment]
Hola Jose, te fijaste si te tira algún error en consola? ahí pareciera como que no se estaría aplicando el **background** con el valor **#13111c** y otra, que navegador estas usando?

**Comment by midudev** [comment]
¿Puedes indicar la versión del navegador que estás usando?
¿Puedes abrir las herramientas de desarrollo y ver si existe algún error?

Gracias.

**Comment by HolaJose2** [comment]
> Entré a la pagina para ver el curso, y se ve todo blanco.
> 
> ![image](https://user-images.githubusercontent.com/110427144/234131295-fde9a075-5c49-4b8f-a91b-2d66a3630549.png)
