### ISSUE TITLE
Error en la segunda pregunta del apartado "Operadores lógicos en JavaScript" Mi respuesta debería ser tomada por buena

### ISSUE THREAD

**Issue by PcMant** [midudev/aprende-javascript-problemas#167]
Mi respuesta debería de haber sido aceptada `1500 - 0.25 * 1500 <= 1150`, y, sin embargo, según esto, la respuesta correcta es `1500 * 0.75 <= 1150` que a pesar de obtener el mismo valor, no entiendo el porqué compararlo con su 75% del precio cuando se trata de un descuento del 25%, por eso yo obtengo el 25% y luego lo resto a 1500.

Además, ahora que me acabo de dar cuenta solo me aceptan en la primera respuesta el operador lógico and representado como `&&` y no como `AND`.

**Comment by Dario-Elguero** [comment]
Me paso lo mismo con respecto a la solución con el descuento, ahora con respecto a lo del AND es claro que solo te va funcionar como && ya que así se representa el AND en JavaScript.

**Comment by PcMant** [comment]
Respecto a lo de representar AND con && tienes razón, por lo general yo acostumbro a representarlo como &&, por eso en un primer momento me lo acepto, además tampoco acepta representar OR con la palabra OR, tocaría usar || para OR, si no recuerdo mal en PHP lo acepta representado de ambas formas y en otros lenguajes, de ahí vino mi confusión. Gracias.

**Comment by AntonioGB1** [comment]
Con respecto a tu respuesta: ****1500 - 0.25 * 1500** <= 1150**  es correcta, sin embargo se procura que el código siempre sea mas legible y simplificado, a lo mejor por eso es que no tomo en cuenta las demás posibilidades de respuestas sino la mas conveniente. Sobre el porque no entiendes el porque ocupar el 75%, el ejercicio solo te pide escribir un código que diga si se puede comprar,  no que calcules el  25% y lo restes, como dije al principio se busca que el código siempre sea lo mas entendible y simplificado. @PcMant

**Comment by PcMant** [comment]
Mea culpa, en su momento no me di cuenta pero ahora lo veo, lo multiplica por 0,75 para compararlo con el 75%, debido a que 100-25=75, para mi ambas soluciones son claras y simples, pero siendo más breve la que ofrece el curso como solución, sin embargo yo creo que ambas deberían ser consideradas como buenas.
