### ISSUE TITLE
Proposed graphic interface

### ISSUE THREAD

**Issue by yasielhp** [midudev/aprende-javascript-problemas#175]
¡Hola @midudev! Espero que estés muy bien. Quería compartir contigo esta propuesta de interfaz de usuario que he creado para el proyecto. Me gustaría destacar lo bien que lo has hecho hasta ahora. Si te gusta, puedes usar esta interfaz para este proyecto o para futuros proyectos. Si tienes alguna pregunta o comentario, por favor házmelo saber. 

Adjunto algunas capturas y un enlace de Figma para que puedas ver más detalles: https://www.figma.com/proto/UuM2S83M8sj3n93tbIiTh3/Website-%7C-aprendejavascript?page-id=7%3A458&node-id=7-1609&viewport=781%2C657%2C0.25&scaling=scale-down&starting-point-node-id=7%3A1796
![Clasificación](https://user-images.githubusercontent.com/8173924/234601290-9adc33d9-505e-4302-acb3-2c28bd73af33.jpg)
![Curso - Introducción - ¿Qué es JavaScript_ - Examen - 1](https://user-images.githubusercontent.com/8173924/234601318-5607b491-fd4f-43da-adfb-82133a024c21.jpg)
![Curso - Introducción - ¿Qué es JavaScript_ - Examen - End](https://user-images.githubusercontent.com/8173924/234601326-cfd79318-9c93-4d65-b554-52ea42711a1c.jpg)
![Curso - Introducción - ¿Qué es JavaScript_ - Examen](https://user-images.githubusercontent.com/8173924/234601329-8238828f-4d1d-4c52-9bb0-19a4f71de618.jpg)
![Curso - Introducción - ¿Qué es JavaScript_](https://user-images.githubusercontent.com/8173924/234601333-aa3173eb-7e2f-4dce-8d7c-882123239923.jpg)
![Curso - Introducción](https://user-images.githubusercontent.com/8173924/234601342-3ba172ce-c1dd-4a35-b8a9-8f03b80fee26.jpg)
![Curso](https://user-images.githubusercontent.com/8173924/234601347-9bfb23a2-6ace-46c4-9d17-8a50bd99968e.jpg)
![Desafíos](https://user-images.githubusercontent.com/8173924/234601352-21d0a9d9-c386-4260-8fca-3baaf59cbbfb.jpg)
![Inicio](https://user-images.githubusercontent.com/8173924/234601356-a98b13b1-ae44-44ff-bea7-6f7fd754960c.jpg)
![Login](https://user-images.githubusercontent.com/8173924/234601359-337425c9-a068-454d-b851-0b72d55a6175.jpg)
![Logros](https://user-images.githubusercontent.com/8173924/234601363-40e554e8-097d-4b79-9663-3c6f30c83464.jpg)

**Comment by midudev** [comment]
¡Muchas gracias! Lo tendré en cuenta. :)
