### ISSUE TITLE
You have an error in the logical operators section.

### ISSUE THREAD

**Issue by Kal-LP** [midudev/aprende-javascript-problemas#177]
https://www.aprendejavascript.dev/clase/introduccion/operadores-logicos

Tenemos un producto en una tienda. Cuesta 1500 y tenemos un descuento del 25%. Tengo 1150€ en mi cartera. Escribe un código que me diga si puedo comprarlo. No uses paréntesis.

Answer : 1500 - 1500 / 4 <= 1150

Note: without using parentheses.

Check it out!

**Comment by midudev** [comment]
Repetido.
