### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by lherrer5** [midudev/aprende-javascript-problemas#196]
Hola
Acabo de terminar todos los temas de las semana 2 y al llegar al final se puso en balnco y arroja error 404.
Muchisimas gracias por todo lo q haces por quienes estamos aprendiendo. 
Explicas de forma q es realmente fácil entender, asimilar e interiorizar los conceptos.

**Comment by midudev** [comment]
Ya está arreglado. Esa clase no está disponible todavía.
