### ISSUE TITLE
Apartado FOR

### ISSUE THREAD

**Issue by JSONIsaac** [midudev/aprende-javascript-problemas#197]
En el apartado de for no tienes un video no se si se haya olvidado

**Comment by 64Forever** [comment]
Encontré un pequeño error en el apartado for, en el examen interactivo, en la solución aparece clavefor escrito todo junto sin el espacio

![ClaveFor](https://user-images.githubusercontent.com/37845241/235080942-5499236f-7dc5-4a0d-9651-33bf9e2e7396.png)

**Comment by midudev** [comment]
Subiré el vídeo este fin de semana que ahora estoy fuera. He arreglado también el typo.

**Comment by 64Forever** [comment]
Me acabo de dar cuenta que hay otro un poco más arriba el que dice  buclefor
