### ISSUE TITLE
Tu primera función

### ISSUE THREAD

**Issue by Paolopier** [midudev/aprende-javascript-problemas#200]
Al clicar para ir a Tu primera función da error 404 y toda la pantalla en blanco

<img width="953" alt="tu primera funcion" src="https://user-images.githubusercontent.com/79837220/235113211-62fecae2-b7df-4f78-ba4c-7eee00858f9e.png">

**Comment by midudev** [comment]
Es normal, ya que la clase no está disponible todavía. Pondremos un mejor 404.
