### ISSUE TITLE
respuesta incorrecta

### ISSUE THREAD

**Issue by ghedzko** [midudev/aprende-javascript-problemas#202]
en la seccion de While , la pregunta:"¿Cuántas veces saldrá en consola la palabra 'Café' while?"
tiene la respuesta equivocada!!!

**Comment by midudev** [comment]
¿Puedes explicar tu respuesta?

**Comment by ghedzko** [comment]
Si , perdon si no fui claro:
 el codigo propuesto en la pregunta es:
`let drinkCoffee = 0

while (drinkCoffee < 10) {
  drinkCoffee = drinkCoffee + 1
  
  if (drinkCoffee === 8) { break }
  if (drinkCoffee === 5) { continue }

  console.log('Café')
}`
ahora la respuesta correcta sería 7, pero si presiono esa sale que es incorrecta y sale correcta la que dice "6"

**Comment by Blackpachamame** [comment]
> Si , perdon si no fui claro: el codigo propuesto en la pregunta es: `let drinkCoffee = 0
> 
> while (drinkCoffee < 10) { drinkCoffee = drinkCoffee + 1
> 
> if (drinkCoffee === 8) { break } if (drinkCoffee === 5) { continue }
> 
> console.log('Café') }` ahora la respuesta correcta sería 7, pero si presiono esa sale que es incorrecta y sale correcta la que dice "6"

Comienza con drinkCoffee = 0,
Antes de las alternativas la variable aumenta en 1,
Por lo que 

| Inicio del white | Dentro del white  | console.log | Cantidad |
|:-------------: |:---------------:| :-------------:| :-------------:|
| 0 | 1 | sí | 1 |
| 1 | 2 | sí | 2 |
| 2 | 3 | sí | 3 |
| 3 | 4 | sí | 4 |
| 4 | 5 | no | 4 |
| 5 | 6 | sí | 5 |
| 6 | 7 | sí | 6 |
| 7 | 8 | no | 6 |

Total de veces que sale la palabra = 6

**Comment by YurandCL** [comment]
Hola @ghedzko, quizá yo te pueda explicar porque pasa esto
El bucle se ejecutará de manera normal las primeras 4 veces, luego de eso, `drinkCoffe = 4` entonces entra al bucle:
1: se le suma uno entonces ahora `drinkCoffe = 5`
2: se lee la condicion `drinkCoffe === 8` la cual devuelve `false`, no pasa nada y continuamos con la siguiente línea
3: se lee la condicion `drinkCoffe === 5`la cual devuelve `true`, ejecutamos la condición.
4: `continue`, la palabra reservada para omitir todo lo que este por debajo, y continuar con una nueva iteración, por lo tanto no se ejecuta el `console.log('cafe)`

Entonces en la sexta iteración habrá impreso 5 veces.
En la séptima iteración habrá impreso 6 veces

En la octava iteración se cumple la condición  `drinkCoffe === 8` por lo que el bucle terminará ahí, y no se ejecutará el `console.log('cafe')`.

por este motivo quedamos en `6` como respuesta correcta

Te adjunto una captura del código ejecutado en consola

Espero te haya servido :)

![bucle_while](https://user-images.githubusercontent.com/40153830/235190609-d2fb43eb-e710-46c9-94fe-47e909c10588.png)

**Comment by ghedzko** [comment]
Hola!!! gracias por tomarte el tiempo para explicarme. Lo probe tanto en la consola como en RunJs y  me sigue dando 7, de hecho 7 fué la primer opción que por lógica me pareció correcta.  
<img width="284" alt="Captura de Pantalla 2023-04-28 a la(s) 23 00 19" src="https://user-images.githubusercontent.com/47998775/235278608-f3e0df99-c99f-4be5-8d7e-425b104b6a27.png">
<img width="623" alt="Captura de Pantalla 2023-04-28 a la(s) 22 59 15" src="https://user-images.githubusercontent.com/47998775/235278611-f92fd1d2-8bce-4cc5-9f42-cc43e801f752.png">

**Comment by ghedzko** [comment]
Bien!! no me había dado cuenta que se salto el 5!! jaja Gracias!!!
