### ISSUE TITLE
Clase de console.log no funciona adecuadamente 

### ISSUE THREAD

**Issue by Josephvm13** [midudev/aprende-javascript-problemas#205]
![image](https://user-images.githubusercontent.com/115128691/235190418-a152098c-ce77-4f67-b6c9-8aeb3f35c4f9.png)

quería pasar a la siguiente clase pero la página se quedaba en blanco y al abrirla directamente de los titulos de la página inicial me aparece esa információn

**Comment by Efredis** [comment]
Confirmo bug.
![image](https://user-images.githubusercontent.com/58520564/235192028-65e83ada-df17-4dc4-8e34-77eff71f0f99.png)

**Comment by Blackpachamame** [comment]
Justo estaba haciendo el mismo post lol
Dejo lo que me muestra la consola
![image](https://user-images.githubusercontent.com/70725851/235193317-f1dee59b-964b-4c75-a1d1-ea7b24b57c02.png)

**Comment by RiverIndians** [comment]
Venía a esto también... Al acabar el primer tema ('Condicional if') del segundo bloque ('Estructuras de control') da el logro "Ilustración del logro desbloqueado ¡A jugar con la consola 🎮!
¡A jugar con la consola 🎮!
28 de abril de 2023
¡Ya sabes qué es el console.log! Eso es la mitad para saber programación." Como si hubiésemos finalizado el apartado del console.log.
