### ISSUE TITLE
Error en el tema de Console log de la Introducción

### ISSUE THREAD

**Issue by Blackpachamame** [midudev/aprende-javascript-problemas#206]
Al entrar me sale el mensaje de: **Application error: a client-side exception has occurred (see the browser console for more information).** Y en la consola muestra lo siguiente: 
![image](https://user-images.githubusercontent.com/70725851/235193317-f1dee59b-964b-4c75-a1d1-ea7b24b57c02.png)

**Comment by Albaric0que** [comment]
Confirmo. A mi tambien me ha pasado.
