### ISSUE TITLE
Boton siguiente clase

### ISSUE THREAD

**Issue by ferwinfuze** [midudev/aprende-javascript-problemas#210]
Cuando se da click en el botón de siguiente clase y la clase no esta habilitada aún, no se muestra ningún mensaje de error, sino que sale una pagina en blanco y no permite realizar ninguna acción.

**Comment by midudev** [comment]
![image](https://user-images.githubusercontent.com/1561955/235294136-f8f8f271-faed-47bc-8c62-2b0566fd6d96.png)

Añadida nueva página de error.
