### ISSUE TITLE
Error al ingresar a clase de "console.log" en el modelo 1

### ISSUE THREAD

**Issue by felipeVerger** [midudev/aprende-javascript-problemas#219]
Cuando ingresas a la ultima leccion llamada "console.log" en el modulo uno(Introduccion) aparece un error que dice "Application error: a client-side exception has occurred (see the browser console for more information)."

**Comment by ssheduardo** [comment]
Confirmo el error,

![image](https://user-images.githubusercontent.com/1160138/235243138-cb470f7c-5aba-4fd6-85fc-53222665f0ed.png)

**Comment by MiguelViHe** [comment]
confirmo
