### ISSUE TITLE
Dice "que incrementa el valor de i" y debería ser "que incrementa el valor de number"

### ISSUE THREAD

**Issue by kanazawa-dev** [midudev/aprende-javascript-problemas#220]
Debería ser number y no i, puede confundir a quien este aprendiendo por primera vez

- ![Captura de pantalla 2023-04-28 a la(s) 14 50 07](https://user-images.githubusercontent.com/105248329/235229430-f8082e6a-2160-4135-8b73-45336faded05.png)

**Comment by midudev** [comment]
Arreglaod.
