### ISSUE TITLE
Ejercicio de codigo interactivo Operadores de comparacion

### ISSUE THREAD

**Issue by INGCapaDev** [midudev/aprende-javascript-problemas#221]
El fallo que encontre es que al momento de dar click en ver solucion, no te muestra ninguna solucion solo me aparece 'respuesta correcta' anexo imagen: 
![image](https://user-images.githubusercontent.com/114124075/235245094-ce37218c-e9cb-43e2-8fd8-bc24c5c9d15b.png)

Opcional ( no se si sea a proposito)
En el ejercicio 'Comprueba que 0 es igual a 0' al colocar `0 == 0` lo marca como erroneo.

**Comment by INGCapaDev** [comment]
Acabo de comprobar y esto pasa cuando escribes en el input antes de darle a ver solucion, si le das a ver solucion de primeras funciona correctamente

**Comment by midudev** [comment]
Repetido.
