### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by pafg93** [midudev/aprende-javascript-problemas#223]
Al momento de querer de entrar a la clase Console.log, se queda colgado y solo muestra el fondo sin mostrar la lección.

**Comment by wolfogan** [comment]
A mi aparece el mismo error: pero con este mensaje y en la consola parece algo de la destructuracion.

![console-log-error](https://user-images.githubusercontent.com/7019532/235268741-b1cbb7cd-584d-45f0-9957-0b33ae41a8e3.png)
