### ISSUE TITLE
Error de sonido en audífonos inalambricos 

### ISSUE THREAD

**Issue by Tuiiikj** [midudev/aprende-javascript-problemas#226]
Hola midu, buenos días, tardes o noches, el sitio web tienes un error cuando uso audifonos inalambricos ya; he probado el sitio web con distintos audífonos inalambricos y en todos ellos tiene el mismo error.
Bueno muchas gracias por apoyar con tus cursos gratuitos en este caso el curso de js, muchas gracias por todo lo que haces; bendiciones 😊.

**Comment by midudev** [comment]
¿Y cuál es el error? Yo uso audífonos inalámbricos y no tengo ningún problema. 😅
