### ISSUE TITLE
No cargan los video de las primeras clase en edge con la Versión 112.0.1722.48

### ISSUE THREAD

**Issue by KewinBarboza** [midudev/aprende-javascript-problemas#23]
![image](https://user-images.githubusercontent.com/32785129/233431990-8b4c1d79-77d5-42fe-99b6-8f6d5cb2a15a.png)

**Comment by danirupe** [comment]
The videos are still not loading at all. @midudev 

My environment:
Browser name and version: Google Chrome 107.0.5304.88
Operating system: Windows 10

**Comment by midudev** [comment]
Ya deberían funcionar @danirupe
