### ISSUE TITLE
Detalle en el enunciado de un titulo en la sección Bucles con while

### ISSUE THREAD

**Issue by Dario-Elguero** [midudev/aprende-javascript-problemas#233]
El titulo: **¿Cuántas veces saldrá en consola la palabra 'Café' while?**
La palabra **_while_** al final no queda bien

podría ser las siguiente opciones:

-  **¿Cuántas veces saldrá en consola la palabra 'Café'?**
- **¿Cuántas veces saldrá en consola la palabra 'Café' en el siguiente ciclo while?**
- **¿Cuántas veces saldrá en consola la palabra 'Café' en el siguiente bucle while?**

**Comment by midudev** [comment]
Arreglado!
