### ISSUE TITLE
Variables "camelCase"

### ISSUE THREAD

**Issue by germangome** [midudev/aprende-javascript-problemas#235]
Hola Midu!
En la seccion de variables cuando explicas "Convenciones y nomenclaturas", en camelCase decis que: **la primer palabara va con minusculas y la segunda en mayusculas.**
Entiendo que solo se escribe en Mayuscula la primer letra y no toda la palabra.
Saludos y gracias ´por tu gran aporte.

**Comment by midudev** [comment]
Arreglado.
