### ISSUE TITLE
en otros navegadores se cae. 

### ISSUE THREAD

**Issue by Secterum** [midudev/aprende-javascript-problemas#24]
Application error: a client-side exception has occurred (see the browser console for more information). 

y en consola muestra 
TypeError: can't access property "call", a[e] is undefined
    NextJS 17
        l
        O
        h
        nI
        s
        h
        s
        s
        o
        lu
        iX
        uA
        uS
        l
        uS
        D
        onmessage
[474-e51cd0ab1b5ee722.js:1:5450](https://www.aprendejavascript.dev/_next/static/chunks/474-e51cd0ab1b5ee722.js)
    NextJS 27
        error
        r9
        callback
        nw
        nS
        am
        av
        aT
        av
        aT
        av
        aT
        av
        aT
        av
        aT
        av
        aT
        av
        aT
        av
        1268/u$/<
        u$
        ux
        uS
        D
        onmessage

**Comment by midudev** [comment]
¿Me puedes decir el navegador? ¿Sigue pasando?

**Comment by Secterum** [comment]
Se solucionó 👍🏻
