### ISSUE TITLE
Errata en ejemplo de código. Clase: "Funciones", ejercicio: "Tu Primera Función"

### ISSUE THREAD

**Issue by ignacio-fm** [midudev/aprende-javascript-problemas#245]
Debería ser un 9 en vez de un 10, pues el `Math.random()` multiplicado por 10 nos proporciona un número decimal con entero del 0 al 9. No es hasta el `const result = rounded + 1` que aumentamos el rango del 1 al 10.

¡Un saludo! 🙂

Captura de pantalla:

![image](https://user-images.githubusercontent.com/91310771/236701146-897c7058-4bc8-47c4-8728-59cd3b7269be.png)

**Comment by Guille-Sanchez** [comment]
@ignacio-fm  A mi parecer la línea indicada no contiene errores. `Math.random()` retorna un valor entre 0 (inclusivo) y 1 (exclusivo) [0, 1), y en esa línea se enuncia que multiplicando` random * 10`, el valor estará comprendido entre los números enteros 0 y 10, (0, 10). En otras palabras, podría llegar hasta 9.999..., pero no alcanza el 10, lo cual aún se encuentra dentro del rango establecido (0, 10). Vale la pena mencionar que en la línea inferior es recien donde se redondea hacia abajo utilizando` Math.floor()`, el cual dicho rango **SI SE ENCUENTRA** en el intervalo [0, 9].

Si es verdad que en esa linea indicada se podria aclarar que el valor podria estar entre 0 (inclusivo) y 10 (exclusivo) [0, 10), el intervalo indicado (0, 10) es correcto al ser un sub-intervalo de [0, 10). Por lo tanto creo que esa linea no necesita modificacion. Saludos!

**Comment by ignacio-fm** [comment]
@Guille-Sanchez ¡Efectivamente!, no hay errata por el hecho de que un número "entre 0 y 9" no contemplaría números con con parte entera 9 y parte decimal superior a 0 (p.e: "9.53"), aún no llegando al entero 10 lo estaríamos excluyendo.

Muchas gracias por comentarlo.

¡Un saludo!
