### ISSUE TITLE
https://www.aprendejavascript.dev/clase/estructuras-de-control/expresiones-y-declaraciones

### ISSUE THREAD

**Issue by technoquo** [midudev/aprende-javascript-problemas#253]
Los videos anteriores si poseen con subtitulo sin embargo este video no tiene subtitulado en la cual provee importante  accesible para las personas sordas que dedican desarrollo web. Nos puede habilitarlo?  Gracias antemano.

**Comment by midudev** [comment]
Los vamos subiendo poco a poco. Paciencia. :)
