### ISSUE TITLE
Error de escritura 

### ISSUE THREAD

**Issue by LuisRaziel** [midudev/aprende-javascript-problemas#254]
En el primer ejercicio de la sección bucle con while al dar la respuesta correcta la explicación del porqué es correcto faltan un espacio entre la palabra bucle y while 

<img width="590" alt="image" src="https://github.com/midudev/aprende-javascript-problemas/assets/22970343/37b82726-7e8c-4cae-8af2-c7ab9dd2841e">

**Comment by midudev** [comment]
Arreglado!
