### ISSUE TITLE
Fallo en la explicación de filter con cadena de texto que contengan la letra "a"

### ISSUE THREAD

**Issue by SrtaOfu** [midudev/aprende-javascript-problemas#262]
En el console.log(stringsWithA) pone que debería aparecer _"['casa', 'coche', 'gato']"_ cuando coche no tiene a y faltan otras que sí la contienen. Debería ser _"['hola', 'adiós', 'casa', 'gato']"_.

<img width="612" alt="FalloExplicaciónEjemplo" src="https://github.com/midudev/aprende-javascript-problemas/assets/123276685/98dec178-889e-4d91-a13a-9639a7130a8b">

**Comment by scherpablo** [comment]
Justo iba a remarcar el mismo. Saludossss...

**Comment by midudev** [comment]
Arreglado!
