### ISSUE TITLE
Métodos y propiedades de Array

### ISSUE THREAD

**Issue by ITSALESDEV2022** [midudev/aprende-javascript-problemas#264]
Hola, recibo un error de "Error en la ejecución del código: Unexpected token 'const'"

const procesarPedido = (pedidos) => {
  const nombreUsuario = pedidos.shift();
  pedidos = ['bebida', ...pedidos];
  pedidos = [...pedidos, nombreUsuario];
  return pedidos;
}

const orden = ['Jose', 'Cerveza', 'CocaCola'];
const pedido = procesarPedido(orden);
console.log(pedido);

**Comment by upsidecodes** [comment]
Me parece raro el código. La consigna dice "Recuerda que debes devolver el array modificado". A mi me dio bien el ejercicio. Lo que tenés que hacer es modificar la función procesarPedido para que simplemente haga un return del array modificado. Una propuesta de solución es esta:

function procesarPedido(pedidos) {
  let newPedidos = pedidos;
  let auxiliar = pedidos[0] //Me guardo el nombre de usuario para usarlo después

  newPedidos.shift();
  newPedidos.unshift("bebida");
  newPedidos.push(auxiliar);

  return newPedidos;
}

Para mi no es un bug.

**Comment by midudev** [comment]
Además:

- Sólo hay que cambiar el código dentro de la función (no usar arrow functions)
- No hay que poner código fuera de la función.
