### ISSUE TITLE
Ejercicio Práctico de iteración de arrays muestra error al enviar respuesta ante una propuesta de solución que es correcta

### ISSUE THREAD

**Issue by upsidecodes** [midudev/aprende-javascript-problemas#265]
Hola Midu
Antes que nada, gracias por todo.
Luego, te mando el error que encontré en el ejercicio de Iteración de Arrays en JavaScript.
Mi propuesta de solución fue:

function sumarPares(numeros) {
  let suma = 0;
  let contador = 0;
  
  while (contador < numeros.lenght) {
    if (numeros[contador] % 2 === 0) {
      suma += numeros[contador];
    }
    contador++;
  }
  
  return suma;
}

Sin embargo, al enviar la respuesta las pruebas me dan error. Es como si no tomara el return de la suma.

![image](https://github.com/midudev/aprende-javascript-problemas/assets/111311191/95a1d1df-231b-45d1-98fa-e8803e59c3d6)

![image](https://github.com/midudev/aprende-javascript-problemas/assets/111311191/680d0ce3-4558-4f5e-9082-56a9f1bdc328)

Lo probé en consola y me dio el resultado esperado, pero en el ejercicio no pasa las pruebas.

Muchas gracias.

**Comment by midudev** [comment]
Está mal escrita la palabra .length:

while (contador < numeros.lenght) {

debería ser:

while (contador < numeros.length) {

**Comment by jesatig** [comment]
Hola ¿Como estas?
Me da error a mi tambien

**Comment by Al3x0704** [comment]
Alguien me lo puede explicar por favor no lo entendí gracias
