### ISSUE TITLE
Problema Ejerecicio de operadores Logicos 

### ISSUE THREAD

**Issue by AndresBarriosGT** [midudev/aprende-javascript-problemas#266]
is:issue is:open Tenemos un producto en una tienda. Cuesta 1500 y tenemos un descuento del 25%. Tengo 1150€ en mi cartera. Escribe un código que me diga si puedo comprarlo. No uses paréntesis.

este ejercicio no acepta el usar paréntesis (1500*0.25)<=1150

**Comment by upsidecodes** [comment]
Pero justamente, ¿La consigna no dice que "No uses paréntesis"?

**Comment by midudev** [comment]
Repetido. Tengo pendiente mirar de mejorar esta sección para que no de problemas.
