### ISSUE TITLE
Métodos y propiedades de Array

### ISSUE THREAD

**Issue by Sircharris** [midudev/aprende-javascript-problemas#268]
Holis, midu. El presente comentario es informar que esta mostrando un error cuando lo pedido por el ejercicio esta correcto. 
![image](https://github.com/midudev/aprende-javascript-problemas/assets/131389138/ce382e4f-1a81-4562-b6b7-0d81af31c8d5)
![image](https://github.com/midudev/aprende-javascript-problemas/assets/131389138/7e06b7ad-3041-40ec-a01e-b59d68716464)
![image](https://github.com/midudev/aprende-javascript-problemas/assets/131389138/1970a5e8-b7ac-4534-baeb-d8d78b694042)
![image](https://github.com/midudev/aprende-javascript-problemas/assets/131389138/4c898d28-2ca7-43ee-89ba-b6a69be36821)
posdata sos un crack, de antemano gracias por todo. Ni mi papa me ha brindado tantas cosas como tu!

**Comment by midudev** [comment]
Pero si tienes mal el test y te lo está diciendo. jajaja

En lugar de 'bebidas' es 'bebida'.

Además hay código de más que podrías eliminar.
