### ISSUE TITLE
Error tipográfico en Ejercicio práctico Ordenamiento de Arrays en JavaScript

### ISSUE THREAD

**Issue by JositoFotos** [midudev/aprende-javascript-problemas#270]
En el resultado que debería devolver hay un error tipográfico, realmente donde aparece '7' debería ser -7.
![image](https://github.com/midudev/aprende-javascript-problemas/assets/134229698/ed440ea6-a8c4-4287-abe4-1b9efb84e292)

**Comment by midudev** [comment]
Bien visto.
