### ISSUE TITLE
ejercicio array

### ISSUE THREAD

**Issue by MiyuBloody** [midudev/aprende-javascript-problemas#274]
en la salida de VSC, me sale correcto, en el ejercicio me dice que no está declarada la funcion:

function procesarPedido(pedido) {

    const cliente = pedido.shift()
    pedido.unshift('bebida')
    pedido.push(cliente)

    return pedido
  }
  const pedidos = ['Carlos', 'café', 'bocadillo', 'patatas', 'postre']
  console.log(procesarPedido(pedidos))

salida por consola vsc:

[ 'bebida', 'café', 'bocadillo', 'patatas', 'postre', 'Carlos' ]

[Done] exited with code=0 in 0.141 seconds

**Comment by ggamboaa** [comment]
Sólo debe completar el código dentro de la función. No crear arreglos ni pasarlos como parámetros. Para eso están los test que Midu agrega para validar si la función está trabajando correctamente.
Saludos!

![image](https://github.com/midudev/aprende-javascript-problemas/assets/63436471/e5127b57-59f7-4ec7-b2dc-e6aada8cc36d)

**Comment by MiyuBloody** [comment]
Ay! Vale gracias!!! Pues lo borro! 

edit:
vale, no puedo borrarlo

**Comment by ggamboaa** [comment]
Funcionó ?

**Comment by MiyuBloody** [comment]
Si, sólo quité la declaración del array como me dijiste y funcionó, gracias

**Comment by jesatig** [comment]
![image](https://github.com/user-attachments/assets/2753ad6a-2ce7-4eae-992d-9abe1baf48b7)
Tengo el mismo problema
