### ISSUE TITLE
Transformación de Arrays en JavaScript

### ISSUE THREAD

**Issue by Dacelisl** [midudev/aprende-javascript-problemas#275]
el ejercicio practico a mi parecer no esta bien, pues a la hora de enviar la respuesta se puede ver la lista de palabras y a palabra que se pretende comparar, tambien el resulado esperado y el obtenido. claramente en el primer ejemplo de la imagen adjunta las palabras 'play', 'balon', 'taza' tienen una extension mayor a 'tio' y el resultado esperado es tan solo 'balon'
![array](https://github.com/midudev/aprende-javascript-problemas/assets/25234259/20740261-11e7-4baa-8a17-6e338b480239)

**Comment by midudev** [comment]
Lo que tienes que usar es el índice de la palabra, no la longitud de la palabra.

En el primer ejemplo, el índice de 'tio' es 4 y 'balon' es la única palabra con longitud mayor que 4.
