### ISSUE TITLE
Error con los arrays en el ejercicio de matrices

### ISSUE THREAD

**Issue by LucianoOPM** [midudev/aprende-javascript-problemas#276]
No sé si sea un error o sea a proposito, pero los ultimos arrays de para hacer los test de las matrices, no contienen comas. 
![imagen_2023-05-25_215448645](https://github.com/midudev/aprende-javascript-problemas/assets/113417117/043c4217-8d92-4545-956c-05e571050b3b)
No sé si sea a proposito o sea un error

**Comment by midudev** [comment]
Arreglado, es un tema solo visual.
