### ISSUE TITLE
Sección: Iteración de Arrays en JavaScript (Solución tirá un error)

### ISSUE THREAD

**Issue by santiruartes** [midudev/aprende-javascript-problemas#277]
Hola Midu, como va? 

He puesto la siguiente solución en el ejercicio de la sección de iteración de arrays y me da error en el test: Error en la ejecución del código: i is not defined. 

En RunJS da todo ok: 

function sumarPares(numeros) {
  let suma = 0
    for (i = 0; i < numeros.length; i++) {
      if(numeros[i] % 2 === 0) {
        suma += numeros[i]
      }
    }
  return suma
}

sumarPares([1, 2, 3, 4])

**Comment by midudev** [comment]
Efectivamente el código no es correcto, ya que estás creando la i como variable global.

En lugar de:
for (i = 0; i < numeros.length; i++) {

Debería ser:
for (let i = 0; i < numeros.length; i++) {
