### ISSUE TITLE
Propuesta de estilos - Lista de clases

### ISSUE THREAD

**Issue by valentinbegnis** [midudev/aprende-javascript-problemas#28]
Hola Midu! Está excelente la página, felicidades 😃

Me gustaría hacer una propuesta de estilos para la lista de clases. Mi idea es la siguiente:

## Lista antes:
<img width="300" height="200" src='https://user-images.githubusercontent.com/66221714/233432257-8e78e0b0-b2f7-472d-b8f4-ed4def60cd10.png'/>

## Propuesta:
<img width="300" height="200" src='https://user-images.githubusercontent.com/66221714/233432947-f29f5429-4634-45d1-ad4a-712140ae16e4.png'/>

### Básicamente, lo que hace *freeCodeCamp*:
<img width="350" height="200" src='https://user-images.githubusercontent.com/66221714/233433422-a5347b77-936c-405a-aef4-c0a34cc027a7.png'/> 

Espero que sea de utilidad.

**Comment by midudev** [comment]
Gracias por la sugerencia. Lo he hecho así al final. :)
<img width="700" alt="image" src="https://user-images.githubusercontent.com/1561955/233623007-5198998e-e87d-4886-a98e-1a2fac0c13fa.png">

**Comment by valentinbegnis** [comment]
Quedó genial Midu!!
