### ISSUE TITLE
Sonido en los dispositivos móviles

### ISSUE THREAD

**Issue by lourdesvaca** [midudev/aprende-javascript-problemas#280]
Hola Midu, qué tal?
Agradeciendo todo el contenido que ofreces  comentarte que he querido seguir el curso desde mi celular pero tengo un problema al reproducir los vídeos, lo que sucede es que al comenzar a reproducir el video el sonido no se logra escuchar.
Cambié de navegador para comprobar si erra error mio y continuaba con lo mismo.

Felicitaciones con el curso!
Bendiciones :D

**Comment by midudev** [comment]
¡Hola Lourdes! He probado en diferentes celulares y no encuentro ningún problema. ¿Qué dispositivo es? ¿Sistema operativo? Sin esa información, es difícil sacar algo en claro.

**Comment by Yarenhi** [comment]
Tengo el mismo problema no se escucha en un Android,  Chrome
