### ISSUE TITLE
La barra de progreso del vídeo no funciona 

### ISSUE THREAD

**Issue by darcardenasp045** [midudev/aprende-javascript-problemas#281]
Hola midu, saludos desde Bogotá, muy buen curso, y en móvil Android, la barra de carga del vídeo no funciona, no controla el vídeo.

Saludos, quedo atento

**Comment by midudev** [comment]
Sin saber qué versión de Android, navegador y demás es imposible que pueda tomar en consideración esto. Igual más adelante lo puedes abrir con la máxima información posible.
