### ISSUE TITLE
Sintasix error "_logaritmo_"

### ISSUE THREAD

**Issue by Alexcastr** [midudev/aprende-javascript-problemas#282]
Fix sintasis error in the algoritmos con arrays part,
instead of say xiste un algoritmo muy popular llamado búsqueda binaria que nos permite encontrar un elemento en un array ordenado en O(log n). Es decir, el número de operaciones que se realizan es igual al **_logaritmo_** del número de elementos del array. 

change logatirmo for algoritmo

**Comment by midudev** [comment]
No estamos hablando del algoritmo. Está bien dicho, estamos hablando del logaritmo que es el proceso de hallar el exponente al cual fue elevada la base para obtener un número.
