### ISSUE TITLE
Las fechas en "Logros" tienen un calendario diferente al mío

### ISSUE THREAD

**Issue by dsilgadosalcedo** [midudev/aprende-javascript-problemas#283]
Creo que se está manejando el calendario de España y no se adapta. Estoy en Colombia y he alcanzado varios logros a las 10pm del 31 de mayo, pero en la lista de logros sale como 1 de junio, seguro es hora española.

![image](https://github.com/midudev/aprende-javascript-problemas/assets/98729190/e5a16a28-f0e9-4eac-9cc5-a59042ee6955)

pd: Gracias por el curso.

**Comment by midudev** [comment]
Repetido.
