### ISSUE TITLE
Background Color in Chrome

### ISSUE THREAD

**Issue by jordislpm** [midudev/aprende-javascript-problemas#285]
hay un error en chrome con el background en chrome, uso otros navegadores y el color es oscuro, pero en chrome el background es blanco, lo cual hace casi imposible de leer y ver el contenido, porque el color de las letras es blanco y amarillo y en el background blanco es casi imposible de ver.

**Comment by midudev** [comment]
He añadido el estilo del fondo en el body a ver si así se arregla.
