### ISSUE TITLE
Ejemplo 2 ".reduce"

### ISSUE THREAD

**Issue by Emiblaiotta** [midudev/aprende-javascript-problemas#289]
En el enunciado dice:
-  Doblar los números pares y sólo quedarnos con los mayores de 5.

El error que encontré es que según el enunciado debería primero seleccionar los números pares, multiplicarlos y después mostrar los que son > 5. 
1 - Se queda con los pares: [2, 4, 6]
2 - Los multiplica * 2 = [4, 8, 12]
3 - Muestra los que son > 5 = [8, 12]

Esto no sucede en el ejemplo, porque según entiendo, primero multiplica  los números del array y luego hace el % . Pero en este caso al multiplicar primero, todos resultan pares y no descarta ninguno al hacer el %. Por ende no concuerda el enunciado con el resultado del ejemplo.

**Comment by midudev** [comment]
Bien visto 👍
