### ISSUE TITLE
Corrección en una palabra

### ISSUE THREAD

**Issue by alejo170** [midudev/aprende-javascript-problemas#290]
Buenas tardes

Por favor corregir en la sintaxis del "for", en vez de la palabra "incremento", colocar "actualización".

![image](https://github.com/midudev/aprende-javascript-problemas/assets/86750984/2e247491-8faf-4dd4-bd52-eec637461df6)

Gracias

**Comment by imTew** [comment]
En el ejercicio Algoritmos con Arrays en la sección Complejidad algorítmica hay un error de redacción que puede prestar a la confusión. 

![image](https://github.com/midudev/aprende-javascript-problemas/assets/122757857/af866508-b1e7-415d-86dc-92d3a274fd04)

Remarque la palabra.

**Comment by midudev** [comment]
Arregladas ambas
