### ISSUE TITLE
Problemas del ejercicio practico en el modulo de ordenar arrays

### ISSUE THREAD

**Issue by JhonatanHernandez96** [midudev/aprende-javascript-problemas#291]
![image](https://github.com/midudev/aprende-javascript-problemas/assets/91023526/bd635ab1-85b6-4951-b940-37b66d154d34)

En el ejercicio practico con solo retornar el array marca correcto en todos los texts.

**Comment by midudev** [comment]
Arreglado!

**Comment by Edward-Chaparro** [comment]
Probé la solución propuesta por @JhonatanHernandez96 pero no me ha funcionado
