### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by Urquii** [midudev/aprende-javascript-problemas#295]
Buenos dias!
Es posible que en el ejercicio interactivo, en esta parte el test no funcione correctamente?Donde indico es posible que falte una ','?

![image](https://github.com/midudev/aprende-javascript-problemas/assets/88881203/72998a65-7a26-4825-b431-06b52ce006f8)

Gracias!

Saludos,

Ivan

**Comment by manuelnieto** [comment]
Es posible. Cuando ejecuto el código queda pegada la página.

**Comment by Urquii** [comment]
A mi los demas test me funcionan correctamente, el único que me falla es ese, por eso tengo la duda! Alomejor yo lo estoy planteando mal, tambien podria ser!

**Comment by Pachix-Dev** [comment]
Creo que tengo el mismo problema 

![matricesArrays](https://github.com/midudev/aprende-javascript-problemas/assets/64230028/6fa9070e-dff2-430e-bd1b-ef7f9723392d)


```
function findJavaScript(matrix) {
  // tu código aquí
  let arrayFC= []
  let find=false
  for(let i = 0; i < matrix.length ; i++){    
    for(let j = 0; j < matrix[i].length; j++){       
      if(matrix[j][i] === "JavaScript"){
        find=true
        return arrayFC = [j,i]
      }
    }   
  }
  if(find === false){
    return arrayFC = [-1, -1]
  }
}
```

hice unas pruebas en run js y si me funciona bien

![matricesArraysRUNJS](https://github.com/midudev/aprende-javascript-problemas/assets/64230028/972a1c37-5a1d-48f2-ad7a-9bbce5f150ac)

**Comment by midudev** [comment]
Lo que te falla es que el expected y el result no dan el mismo resultado. El título es sólo visual.
