### ISSUE TITLE
WTF!? function sortAbsoluteNumbers(numbers)

### ISSUE THREAD

**Issue by johnsoul777** [midudev/aprende-javascript-problemas#298]
Hola Midu no se si es que no he entendido bien el ejercicio, o es un error, adjunto pantallazo
![image](https://github.com/midudev/aprende-javascript-problemas/assets/72218928/2f6cd5d4-0e55-4200-a765-85814663817d)

**Comment by CamiloAlmada** [comment]
Hola @johnsoul777 te falta el return, con eso ya funcionaria correctamente

Saludos

**Comment by johnsoul777** [comment]
Gracias por tu respuesta @CamiloAlmada, si te fijas bien es una función de flecha, y tiene un return implícito, por lo tanto no es necesario usarlo, de todas formas gracias por intentarlo amigo!

Un saludo!

**Comment by CamiloAlmada** [comment]
Si @johnsoul777,  eso lo tengo claro, pero `sortAbsoluteNumbers` no es una arrow function, 
por lo tanto necesita `return numbers.sort((a,b) => ... ) ` 
a ese return me refería, perdón por no aclararlo y dejarlo libre a confusión

**Comment by johnsoul777** [comment]
Bien visto amigo, solucionado, muchas gracias!!!

Un saludo!
