### ISSUE TITLE
Error en la retroalimentacion de la respuesta Objetos > atajos

### ISSUE THREAD

**Issue by elmonoska** [midudev/aprende-javascript-problemas#299]
Hola midu! 
En el modulo de Objetos > atajos; la retroalimentacion de que la respuesta es correcta no corresponde.

![image](https://github.com/midudev/aprende-javascript-problemas/assets/72885173/fa178a6f-b187-4ebb-ad83-1cd2b93c0c67)

**Comment by midudev** [comment]
Arreglado!
