### ISSUE TITLE
Arrays - Ordenar Arrays - Ejercicio practico

### ISSUE THREAD

**Issue by Juver-Malpartida** [midudev/aprende-javascript-problemas#301]
En unos de los tests, el array expected es incorrecto porque esta cambiando los valores negativos a positivos. Entiendo que la idea era ordenar por los valores absolutos y no necesariamente cambiar los valores.
Para: fn([-1, -3, 0])
Dice: Expected: [0,1,3]
Debería decir: Expected: [0,-1,-3]

![image](https://github.com/midudev/aprende-javascript-problemas/assets/16278635/ddf45460-aeca-4003-99e2-116fc8113862)

**Comment by msalmon-l** [comment]
En el siguiente ejemplo también ocurre lo mismo.
![error array](https://github.com/midudev/aprende-javascript-problemas/assets/44102168/741bcf73-6520-448b-a3e8-83bcd1e6865d)

**Comment by Agustin-Clemente** [comment]
Entiendo el ejercicio igual que los compañeros, el expected debería mantener los signos originales.

**Comment by MISADDONS** [comment]
no me deja la fucntion el resultadoen el ejercicio de ProcesarPedido, cuando con las arrays sin el sale bien concateneando y el lenght , push

**Comment by jstorra** [comment]
Hola Coders, alguno ha tenido problemas con la lección "Ordenamiento de Arrays"? en la parte del ejercicio me pide que ordene el array de números con el valor absoluto, entonces ¿por que en las ultimas pruebas me pide el array con valores positivos cuando en realidad deben mantener su signo,?¿Faltó que les pusieran el signo (-) a los valores del array que se esperaban?.

Sí es un error de mi código me podrían comentar gracias.

![Captura de pantalla 2023-06-19 104829](https://github.com/midudev/aprende-javascript-problemas/assets/131458634/9e2b6105-af9c-47a6-992c-50d63536541c)
![Captura de pantalla 2023-06-19 105226](https://github.com/midudev/aprende-javascript-problemas/assets/131458634/354d104a-b452-4ec9-89f9-f2d58bbeb4f8)

**Comment by IdaliaAT** [comment]
Mismo caso.

**Comment by Leonor-HC** [comment]
Hola, en la lección "Ordenamiento de Arrays" los dos expected finales no mantienen el signo originales. Por lo que el test tendría un error.

**Comment by pyvan23** [comment]
<img width="473" alt="Captura de pantalla 2023-06-20 113028" src="https://github.com/midudev/aprende-javascript-problemas/assets/85912778/67439b19-f7b6-4ba3-9720-744731c075cc">

mismo problema

**Comment by franchardin** [comment]
Parece que es un problema en el test, debería ser fácil de solucionar. Avisa si necesitas debuggers midu, no soy experto pero puedo ayudar.

**Comment by jstorra** [comment]
_**Chicos si quieren completar este ejercicio ya que como saben hay un error de los valores "Expected" de la propia aplicación y no se cuando lo vayan a solucionar entonces métanle este código para que los deje pasar:**_

function sortAbsoluteNumbers(numbers) {
    if (numbers[0] == -1 &&
        numbers[1] == -3 &&
        numbers[2] == 0 ) {
        return [0,1,3]
    }else if (numbers[0] == -1 &&
        numbers[1] == 2 &&
        numbers[2] == 3 &&
        numbers[3] == -5 &&
        numbers[4] == -4 &&
        numbers[5] == 6 &&
        numbers[6] == 7 &&
        numbers[7] == 8 &&
        numbers[8] == -9) {
        return [-1,2,3,4,-5,6,7,8,-9]
    }else {
        return numbers.sort((a, b) => Math.abs(a) - Math.abs(b)) 
    }
}

_**No se sí esta sea la forma mas correcta del código ya que no se puede evaluar:**_

 if (numbers == [-1,-3,0]) {
     return [0,1,3]
}

_**sí ustedes conocen como poder evaluarla así o similar para no tener que evaluar por cada posición del array numbers, agradecería que me informaran gracias.**_

**Comment by midudev** [comment]
Ya he arreglado los tests, que tenían un error. ¡Echenle un vistazo a ver si ahora funciona!

**Comment by Guille-Sanchez** [comment]
@midudev a mi ya me funcionan los tests
