### ISSUE TITLE
Posible error en el ejercicio práctico del operador de encadenamiento opcional

### ISSUE THREAD

**Issue by cmorenogonzalez33** [midudev/aprende-javascript-problemas#302]
¿está bien que se espere TRUE cuendo no está definida la variable TREASURE?
![image](https://github.com/midudev/aprende-javascript-problemas/assets/94968881/5d9701fb-c70a-4403-9459-d9ad48ee1a61)

**Comment by Guille-Sanchez** [comment]
Buenas, a mi parecer el ejercicio esta bien planteado y los resultados son correctos.

En el screenshot que muestras has escrito directamente algunos valores como keys en vez de utilizar los parámetros de la función searchInOcean, por lo tanto no tienes el resultado deseado. Favor volver a probar y utilizar los parámetros de la función para que así tu código pueda pasar los tests del ejercicio.

Por cierto, Midu dejo una cascara de banana muy grande que podría confundir a los nuevos y no tan buenos en JS en este ejercicio. La cascara de banana fue el escribir ocean.deep.treasure en el prologo del ejercicio. Tener en cuenta que al utilizar un objeto e intentar acceder a un valor del mismo no es lo mismo escribir objecto.key que escribir objecto.parametro, siendo el parametro una variable que guarda el valor de la key. JavaScript buscara dentro el objecto el valor que tratas de acceder y si pones objecto.parametro JS **NO** evaluara el valor del parametro, directamente buscara  una key llamada parametro y si no la encuentra devolvera undefined.

Mayor información sobre esa posible cascara de banana en la primera clase de Objectos unidad "Acceder a propiedades y métodos de un objeto" disponible en [Aprende JavaScript](https://www.aprendejavascript.dev/clase/objetos/introduccion)

**Comment by guzmanpdro** [comment]
@Guille-Sanchez Caí en ese error y gracias a tu comentario pude salir del barro.

**Comment by midudev** [comment]
Gracias por contestar @Guille-Sanchez

**Comment by cmorenogonzalez33** [comment]
Muchas gracias, Guillermo. Intenté cambiarlo, pero entonces fallaban los
otros tests.
Intentaré de nuevo.
Un cordial saludo.
Cristina
