### ISSUE TITLE
Gracias

### ISSUE THREAD

**Issue by DanielSanchezPinazo** [midudev/aprende-javascript-problemas#303]
Ante todo quería agradecer el tiempo dedicado a un curso gratuito tan bueno. BRAVO. Mi única sugerencia es que en el ejercicio del "Operador de encadenamiento opcional" me iba a volver loco porque en ningún lado del tutorial se explica que para acceder a la propiedad de un objeto con un Sting pasado como parámetro en una función hay que usar corchetes...lo he tenido que encontrar fuera buscando por qué me fallaba todo el rato el ejercicio, ya que lo estaba intentando sólo con los puntos como se hace durante todo el apartado. Sin más. MIL GRACIAS

**Comment by Guille-Sanchez** [comment]
Buenas @DanielSanchezPinazo, en el issue #302 se toco este punto. Pero al ser una duda repetitiva quizas Midu pueda brindar una 'pista' al enunciado del ejercicio mencionando que se usa informacion disponible en el contenido "Acceder a propiedades y métodos de un objeto" disponible en [Aprende JavaScript](https://www.aprendejavascript.dev/clase/objetos/introduccion). Saludos!

**Comment by midudev** [comment]
@DanielSanchezPinazo en el curso sí que se explica, se hace justamente en la clase anterior de introducción de Objetos: https://www.aprendejavascript.dev/clase/objetos/introduccion

Voy a añadir una pista para que la gente lo revise.
