### ISSUE TITLE
Error de redacción - Objetos - Transformar un objeto en un array

### ISSUE THREAD

**Issue by gifrancohe** [midudev/aprende-javascript-problemas#305]
Hola @midudev !

Eres el mejor muchas gracias, sos grande, mucho amor para vos.

Simplemente es un error de redacción.
![image](https://github.com/midudev/aprende-javascript-problemas/assets/17013928/86327bd6-3307-476f-9132-a066e734c339)

Creó que sería **Object.values()** en la primera parte de la oración y no **Object.keys()** para que quizás no haya lugar a dudas.

Por lo que considero así debería quedar la oración:

> Como ves, la diferencia con Object.values() es que este método retorna los valores y Object.keys() retorna las propiedades.

Un abrazo gigante

**Comment by midudev** [comment]
¡Gracias!
