### ISSUE TITLE
Evaluacion estructuras de control while

### ISSUE THREAD

**Issue by capenadiaz** [midudev/aprende-javascript-problemas#306]
Hola profe.

De antemano quiero agradecerte por darnos tu conocimiento gratis, para mi es muy valioso y te entiendo muy bien.

En la evaluación interactiva ¿Cuántas veces saldrá en consola la palabra 'Café'? la respuesta correcta sale 6, sin embargo creo que debería ser 7.

Me corriges si estoy equibocado por favor.

**Comment by Guille-Sanchez** [comment]
Buenas @capenadiaz, la respuesta correcta en verdad es 6 y te explico porque.

Hice correr el código en la consola del navegador y le agregue algunos comentarios y variables para facilitar la explicación. Si puedes ver `console.log('Café')` es llamado normalmente hasta la 4ta iteración. Luego, en la 5ta iteración entra en el `if (drinkCoffee === 5) { continue }` y se salta a la siguiente iteración, la 6ta. Allí vuelve a continuar hasta la iteración 8 en donde entra en el `if (drinkCoffee === 8) { break }`  y sale fuera del loop. Tener en cuenta que la condición `(drinkCoffee < 10)` del while nunca se evalúa en este código porque cuando `drinkCoffee === 8` ya sale de ese loop. Espero haber logrado explicar bien el código.

A modo de comentario, en caso de dudas/consultas te recomiendo escribir en el grupo de [Discord](https://discord.com/invite/midudev) ya que este espacio es mas para reportar errores/dar sugerencias. Saludos!

![image](https://github.com/midudev/aprende-javascript-problemas/assets/122386424/2a4f6546-c730-4d20-b396-b8fb4a6f99f1)

**Comment by midudev** [comment]
Gracias @Guille-Sanchez
