### ISSUE TITLE
Lección Matrices

### ISSUE THREAD

**Issue by ioanjalba** [midudev/aprende-javascript-problemas#309]
![error](https://github.com/midudev/aprende-javascript-problemas/assets/73834007/3d90a5f8-1adf-47c8-8514-068ef9f1df4a)

En la lección de **Matrices**, en uno de los ejemplos de código para reccorer la matriz con foEach, en el console.log del elemento creo que faltaria añadir un "+".

Un abrazo!

**Comment by Guille-Sanchez** [comment]
Buenas @ioanjalba, tanto `console.log('Elemento ', elemento)` como `console.log('Elemento ' + elemento)` son formas apropiadas de imprimir la variable, lo que seria incorrecto es `console.log('Elemento ' elemento)` en el que solo se tiene un espacio

Ejemplo de la pagina:
![image](https://github.com/midudev/aprende-javascript-problemas/assets/122386424/90845e47-141b-4c59-950b-d573e0d6846e)

Ejemplo mencionado por ti:
![image](https://github.com/midudev/aprende-javascript-problemas/assets/122386424/62b0ec20-cfc4-452a-9b83-b03a93a52b2f)

Codigo erroneo:
![image](https://github.com/midudev/aprende-javascript-problemas/assets/122386424/cc921666-6c1d-43c6-9a3c-17419f76f601)

Saludos

**Comment by ioanjalba** [comment]
@Guille-Sanchez No tenia ni idea, muchas gracias!
