### ISSUE TITLE
Error en operador lógico

### ISSUE THREAD

**Issue by paulneo** [midudev/aprende-javascript-problemas#31]
En el ejemplo 3 hay un error  al inicio del texto.

![Screen Shot 2023-04-20 at 11 53 40](https://user-images.githubusercontent.com/19512540/233435329-1099d192-65e0-4191-8af0-148a10c93f54.png)

**Comment by alzuet** [comment]
En esta línea: **|false && true || !true**, sobra el primer _pipe_ (|).

**Comment by midudev** [comment]
✅
