### ISSUE TITLE
Error en conditionals

### ISSUE THREAD

**Issue by JonSegovia** [midudev/aprende-javascript-problemas#312]
Tenemos un error en las opciones disponibles, ya que la primera y la última son iguales. Pero la primera da incorrecto y la tercera de correcto. 

![2023-06-27_10-40](https://github.com/midudev/aprende-javascript-problemas/assets/113635291/e002f565-2716-4d2f-8bc2-f9934ba0a495)

**Comment by Guille-Sanchez** [comment]
Buenas @JonSegovia  El test es correcto. Si no buscas el error capaz no lo veas, a mi me costo, pero el error en la primera opcion mostrada es que el `else ( /*codigo*/)`, parentesis, es una sintaxis incorrecta. `else {/*codigo*/}`, llaves/corchetes, es la sintaxis correcta.

**Comment by JonSegovia** [comment]
claro! incluso a distancia me costó divisar que son paréntesis en lugar de corchetes en este momento. Los anteojos recetados tenían sentido. Gracias!

**Comment by JonSegovia** [comment]
claro! incluso a distancia me costó divisar que son paréntesis en lugar de corchetes en este momento. Los anteojos recetados tenían sentido. Gracias!
