### ISSUE TITLE
error en ejercicio de metodos array.

### ISSUE THREAD

**Issue by Manaure-Sousa** [midudev/aprende-javascript-problemas#313]
![image](https://github.com/midudev/aprende-javascript-problemas/assets/136469772/15bdc899-5d82-422a-ace5-98053021decc)
En la consola del navegador este codigo está cierto, funciona perfectamente, pero en el ejercicio queda con una mensaje de error.

**Comment by Blackpachamame** [comment]
No estás retornando nada en la función, cosa que pide el enunciado.
