### ISSUE TITLE
Soluciones de los ejercicios??

### ISSUE THREAD

**Issue by victor1kenobi** [midudev/aprende-javascript-problemas#315]
Buenas, invierto mucho tiempo en los ejercicios finales... hay en algun logar tips para resolverlos o soluciones para poder avanzar y no quedar atascado?

Gracias

**Comment by mcer23** [comment]
chatgpt 👍

**Comment by pierotti76** [comment]
Hola victor1kenobi, yo soy novato y paso por los mismos inconvenientes que has nombrado. Has encontrado donde acudir para solucionar estos temas?. Saludos y gracias.

**Comment by pierotti76** [comment]
Hola  victor1kenobi , lo de mcer23 funciona , a mi me ayudo bastante. Suerte .

chat.openai.com

**Comment by midudev** [comment]
En el Discord de la comunidad:
https://discord.gg/midudev
