### ISSUE TITLE
No se puede ir a la pagina de Inicio

### ISSUE THREAD

**Issue by orivero83** [midudev/aprende-javascript-problemas#317]
Hola,

No se puede ir a la pagina de Inicio cuando estas haciendo los cursos

Solo se puede ir a la pagina siguiente o anterior.

Podrias dejar el icono de JS que tienes en la esquina superior izquierda en todas las paginas asi uno puedo clicar alli e ir a la pagina de inicio y seleccionar.

**Comment by Guille-Sanchez** [comment]
Hola @orivero83 en verdad si se puede ir a la pagina de inicio. Al entrar en cada unidad, en el header aparece una flecha hacia atras, solo debes apretarla. En caso de que no te aparezca, favor dar mas detalles. Saludos

![image](https://github.com/midudev/aprende-javascript-problemas/assets/122386424/c666e364-2e9b-428b-965f-773096b7edec)
