### ISSUE TITLE
Error sección Arrays. Se queda en "Comprobando..."

### ISSUE THREAD

**Issue by nicoraffone** [midudev/aprende-javascript-problemas#319]
for (let i = 0; i = numeros.length; i++){
    if (numeros[i] % 2 === 0){
      suma += numeros[i]
    }
  }

Ese es mi código. Y no pasa a la siguiente sección. Si pongo un código errado hace la corrección bien pero si es correcto se bugea

**Comment by Guille-Sanchez** [comment]
@nicoraffone existe un pequeño error en tu codigo, vamos a analizarlo juntos

En el for-loop que aplicaste, acordate que hay tres partes: crear la variable, condicionar la variable, hacer variar a la variable.

Analicemos tu codigo.
let i = 0, crear la variable ✅ 
i = numeros.length, condicionar la variable ❔
i++, hacer variar la variable ✅ 

Favor revisar esa parte de tu codigo. Una pista, actualmente estas haciendo un loop infinito, por eso el test no se termina de ejecutar. Pero es una buena observación @midudev no se si habria alguna forma de ponerle un timeout o algo que muestre un error al hacer un loop infinito

**Comment by ericmonroydev** [comment]
solo hay que hacer el bucle de números y retornarlo

function sumarPares(numeros) {
  let suma = 0;
  // tu código aquí
  numeros.forEach((num) => {
    if(num % 2 === 0 ){
      suma += num
    }
  })
  
  return suma;
}
