### ISSUE TITLE
ejercicios arrays

### ISSUE THREAD

**Issue by Manaure-Sousa** [midudev/aprende-javascript-problemas#320]
![image](https://github.com/midudev/aprende-javascript-problemas/assets/136469772/dbeb5a41-c3e5-4b2d-8e17-efc591e7842e)

Cómo puede hacerlo para quedarse completado? porque ya ejecuté el código corectamiente pero no logre. Qué forma debo escribir el codigo para funcionar?

```
const pedido = ['Manaure', 'pollo', 'pizza']
procesarPedido(pedido)
function procesarPedido(pedidos) {
  const nombre = pedido.shift()
  pedido.unshift("bebida")
  pedido.push(nombre)
}
console.log(pedido)
```
el codigo en terminal funciona perfectamente.

**Comment by Guille-Sanchez** [comment]
@Manaure-Vasconcelos Buenos dias! El codigo que proporcionaste es correcto, solo le falta retornar la variable al final de la función. En caso de tener mas dudas o consultas te recomiendo escribir en el grupo de discord. Este espacio es mas dedicado a el exponer errores/posibles-mejoras a la pagina. Saludos!

**Comment by midudev** [comment]
Como te han comentado, el problema es que la función no devuelve nada.
