### ISSUE TITLE
Error test "Transformación de Arrays en JavaScript"

### ISSUE THREAD

**Issue by Senesero** [midudev/aprende-javascript-problemas#321]
Dado el enunciado, los Expected de los test no son correctos:

![image](https://github.com/midudev/aprende-javascript-problemas/assets/10695078/0818488e-93eb-40e3-be1a-e138d389fd58)

Dado que para el ejemplo "fn(['play', 'balon', 'asa', 'taza', 'tio'], 'tio')" la longitud de tio es 3, con lo que "play", "balon" y "taza" deberían de estar en Expected al tener longitud mayor que 3

Lo mismo pasa con "fn(['play', 'midu', 'asa', 'libro', 'lino', 'dino'], 'dino')" con longitud de dino 4 y expected teniendo que estar "libro"

**Comment by Guille-Sanchez** [comment]
@Senesero Buenos dias. Creo que hubo un mal entendido en el enunciado del ejercicio.

Debes buscar el indice de la palabra en la lista y usar ese indice para hacer las comprobaciones. Siguiendo el ejemplo mencionado: "fn(['play', 'balon', 'asa', 'taza', 'tio'], 'tio')", en el array 'tio' tiene el indice 4 y solo balon tiene mas de 4 letras. Por lo tanto el valor esperado por el test es el correcto. Saludos

**Comment by hansjoao14** [comment]
Guille creo que no tiene sentido ya que en las pruebas que siguen no se utiliza la longuitud de las palabra, creo que quiere que se haga dependiendo de la cantidad de palabras que hay en el array words ("indice")

**Comment by hansjoao14** [comment]
![image](https://github.com/midudev/aprende-javascript-problemas/assets/47186770/9452e490-cf18-43d0-be59-3ab5c9a52dc2)

**Comment by hansjoao14** [comment]
> @Senesero Buenos dias. Creo que hubo un mal entendido en el enunciado del ejercicio.
> 
> Debes buscar el indice de la palabra en la lista y usar ese indice para hacer las comprobaciones. Siguiendo el ejemplo mencionado: "fn(['play', 'balon', 'asa', 'taza', 'tio'], 'tio')", en el array 'tio' tiene el indice 4 y solo balon tiene mas de 4 letras. Por lo tanto el valor esperado por el test es el correcto. Saludos

Guille creo que no tiene sentido ya que en las pruebas que siguen no se utiliza la longuitud de las palabra, creo que quiere que se haga dependiendo de la cantidad de palabras que hay en el array words ("indice"), explicado eso el ejercicio tendria una solucion asi 

![image](https://github.com/midudev/aprende-javascript-problemas/assets/47186770/e651da76-d088-4da1-9aff-f0c48caddabe)

**Comment by midudev** [comment]
Hay que buscar el índice, no la longitud de la palabra. Lo dice el enunciado.

Si el índice te devuelve `3`, entonces buscas las palabras mayores de 3.
