### ISSUE TITLE
Error - Ejercicio Práctico Métodos y Propiedades de Arrays

### ISSUE THREAD

**Issue by wastewalker** [midudev/aprende-javascript-problemas#322]
En la lección _Métodos y Propiedades de Array_ en la parte del ejercicio práctico no pasa la última prueba ya que el resultado esperado está al revés, no sé si es algún error, o es que se debe programar para que el resultado también salga al revés, cosa que no se enseñó como hacer eso en la lección. Adjunto captura para expresar mejor el incidente, que a su vez, no deja marcar como completada la lección y se queda en progreso. Saludos cordiales.
![Captura error](https://github.com/midudev/aprende-javascript-problemas/assets/22105922/eaacf890-f84a-4ed9-9c5a-d0ae025ec047)

**Comment by kyupp** [comment]
Buenas disculpa la molestia en mi caso fuciona de manera correcta, entonces, si no me equivoco te falta el push del cliente, saludos 👍🏻 
![Screenshot from 2023-07-12 19-33-40](https://github.com/midudev/aprende-javascript-problemas/assets/79992458/83eef1e4-cd5b-4fed-b13a-3f81f5313802)
