### ISSUE TITLE
typeof userName || typeof "userName"

### ISSUE THREAD

**Issue by pierotti76** [midudev/aprende-javascript-problemas#323]
typeof "userName" es la manera en que la consola reconoce este ejercicio y en el curso pone como error si lo escribimos igual y solo lo da por valido sin los "". Cual es el error? Gracias.

**Comment by midudev** [comment]
El error es que hay que ponerlo sin los ", ya que lo que queremos es ver el typeof de la variable, no de la cadena de texto.

typeof userName // -> dará el tipo de la variable userName
typeof "userName" // -> string, ya que "userName" es un string

**Comment by pierotti76** [comment]
Muchas gracias, tu trabajo me ayuda mucho ya que como principiante ante tanta Info uno se marea en ocasiones.
Saludos.

**Comment by pierotti76** [comment]
Hola midudev .Quería preguntarte otra cosa sobre los "métodos de búsqueda de array". Intento desarrollar el ejercicio pero dices que usemos el metodo endsWith() y cuando lo intento me pone que no es una función . ya no se por donde van los tiros como quien dice. Te dejo captura y copio lo que empecé porque no logro resolverlo. Saludos y Gracias.


// function acabanEnA(words = ['asa', 'taza', 'casa'])
{ const todosTerminanConA = words.every
(words =>words ==='a')
todosTerminanConA.endsWith('a') 

}

![Captura web_30-7-2023_173355_www aprendejavascript dev](https://github.com/midudev/aprende-javascript-problemas/assets/138127722/6703b85c-b66d-4673-838e-c73b7dea72e9)
