### ISSUE TITLE
ejercicio de arrays sin lograr que de resultado

### ISSUE THREAD

**Issue by pierotti76** [midudev/aprende-javascript-problemas#328]
Hola buenas, no logro saber si esta bien mi código ya que en el ejercicio no me lo acepta pero si lo hacen en las otras consolas que pruebo. Gracias. 

const comidas=['pizza']
const cliente=['Julian']
const bebidas=['cocacola']
const contenidoPedidos =[...cliente,...bebidas,...comidas]
procesarPedido(contenidoPedidos)
contenidoPedidos.shift()
contenidoPedidos.unshift() 
contenidoPedidos.push(cliente[0])    
 
    function procesarPedido(pedidos) {
}console.log(pedidos)

**Comment by Crenxm** [comment]
¡Hola! Hace poco pase por esa parte, esto aprendiendo apenas, pero voy a intentar ayudarte. Por lo que veo estas en el ejercico "Métodos y propiedades de Array"  En los ejercicos ya nos dan el Array (no lo tenemos que crear nosotros), y nos piden que creemos la función para reorganizarlo.

- El primer elemento lo sacamos del array, ya que es el nombre del cliente.
- Añadimos al principio del array la cadena de texto "bebida", ya que es una promoción que tenemos.
- Después añadimos al final del array el nombre del usuario que sacamos antes.

```js
function procesarPedido(pedidos) {
  const primerElemento = pedidos.shift(); // El primer elemento lo sacamos con el metodo .shift() y lo guardamos en una const  
  pedidos.unshift("bebida");  // con el metodo .unshift() agregamos un string al inicio del array 
  pedidos.push(primerElemento) // el primer elemento que anteriormente guardamos lo añadimos al final con el metodo .push()
  return pedidos
}
```

**Comment by pierotti76** [comment]
Hola ,muchas gracias. Si veo que la idea la entendí solo que me lie metiéndome a hacer el desarrollo yo mismo . Gracias.
________________________________
De: Crenxm ***@***.***>
Enviado: martes, 25 de julio de 2023 1:08
Para: midudev/aprende-javascript-problemas ***@***.***>
Cc: pierotti76 ***@***.***>; Author ***@***.***>
Asunto: Re: [midudev/aprende-javascript-problemas] ejercicio de arrays sin lograr que de resultado (Issue #328)


¡Hola! Hace poco pase por esa parte, esto aprendiendo apenas, pero voy a intentar ayudarte. Por lo que veo estas en el ejercico "Métodos y propiedades de Array" En los ejercicos ya nos dan el Array (no lo tenemos que crear nosotros), y nos piden que creemos la función para reorganizarlo.

  *   El primer elemento lo sacamos del array, ya que es el nombre del cliente.
  *   Añadimos al principio del array la cadena de texto "bebida", ya que es una promoción que tenemos.
  *   Después añadimos al final del array el nombre del usuario que sacamos antes.

function procesarPedido(pedidos) {
  const primerElemento = pedidos.shift(); // El primer elemento lo sacamos con el metodo .shift() y lo guardamos en una const
  pedidos.unshift("bebida");  // con el metodo .unshift() agregamos un string al inicio del array
  pedidos.push(primerElemento) // el primer elemento que anteriormente guardamos lo añadimos al final con el metodo .push()
  return pedidos
}
