### ISSUE TITLE
Error ortográfico

### ISSUE THREAD

**Issue by nescalada** [midudev/aprende-javascript-problemas#330]
Gracias por los cursos. Notifico el siguiente error ortográfico:

<img width="566" alt="Objetos, Encadenamiento, error en enunciado ejercicio" src="https://github.com/midudev/aprende-javascript-problemas/assets/7088028/4cf41147-487d-4e44-9584-34964b18327b">

¡Saludos!

**Comment by midudev** [comment]
Fixed
