### ISSUE TITLE
problemas con el ejercicio de metodos de busqueda de arrays

### ISSUE THREAD

**Issue by pierotti76** [midudev/aprende-javascript-problemas#331]
Crear una función que reciba un array de palabras y devuelva true si todas las palabras terminan con la letra "a" y false si al menos una palabra no termina con la letra "a".

Usa el [método endsWith() de string](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) para resolverlo.
 Cuando trato de usar endsWith() me pone que no es una función .No se como avanzar porque si no lo uso no me reconoce el código como valido y es un poco frustante de verdad. Si alguien puede darme una mano se agradece ya que soy muy novato y quiero seguir avanzando.
Gracias y saludos

**Comment by midudev** [comment]
Seguramente el problema es que no estás usando el método endsWith sobre un string, si no sobre otro tipo de dato.

**Comment by pierotti76** [comment]
Hola midudev, quería preguntarte algo ,mas bien pedirte consejo si es posible.
 Soy novato como veras, y estoy muy interesado por seguir aprendiendo, pero es cierto que en ocasiones no puedo desarrollar bien los ejercicios y no ser si seguir el curso o volver a empezarlo para ver porque no logro superarlos, no se si es perder el tiempo volver atrás cada vez que paso por eso o mas bien conviene seguir adelante y ya habrá otro momento donde lo veré mas claro. Que me recomiendas con tu experiencia? ya que no están las soluciones de los ejercicios y dedico mucho tiempo a buscar on line ayuda y no siempre se resuelve,  y no logro saber que hago mal en concreto. Un saludo y gracias.

**Comment by pierotti76** [comment]
Otro tema, encontré como solucionar los problemas y así ver en que fallo pero al ejecutarlo en la pagina me lo da como error sin embargo en la consola lo da valido. Pego el ej . Gracias
Ej consola :
function todasTerminanEnA(arrayDePalabras) {
    return arrayDePalabras.every(palabra => palabra.endsWith("a"));
}

const palabras1 = ["casa", "mesa", "silla"];
const palabras2 = ["ventana", "puerta", "piso"];

console.log(todasTerminanEnA(palabras1)); // Devolverá true
console.log(todasTerminanEnA(palabras2)); // Devolverá false

ERROR en la pagina : mismo codigo pero aca da este error==> Error en la ejecución del código: todasTerminanEnA is not defined


Usa el [método endsWith() de string](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) para resolverlo.

function todasTerminanEnA(arrayDePalabras) {
    return arrayDePalabras.every(palabra => palabra.endsWith("a"));
}

const palabras1 = ["casa", "mesa", "silla"];
const palabras2 = ["ventana", "puerta", "piso"];

console.log(todasTerminanEnA(palabras1)); // Devolverá true
console.log(todasTerminanEnA(palabras2)); // Devolverá false

Enviar respuesta
Tests
Error en la ejecución del código: todasTerminanEnA is not defined

**Comment by pierotti76** [comment]
Hola Midu ,sigo con  el mismo problema que te comente en el texto anterior. Ahora el caso es en el ejercicio de Transformación de Arrays en JavaScript.
Pego el código que en consola me lo admite pero en la del ejercicio me da error. Gracias


function buscaPalabras(words, uvas) {
   const indice = words.indexOf("uvas");
    const longitudIndice = uvas.length;
  if ( longitudIndice > 0) {
      const palabrasMasLargas = words.filter(palabra => palabra.length > longitudIndice);
    return palabrasMasLargas;
  }else {
      return [];
  } 
}
const listaDePalabras = ["manzana", "banana", "naranja", "uvas", "pera"];
const palabraObjetivo = "uvas";
const resultado = buscaPalabras(listaDePalabras, palabraObjetivo);
console.log(resultado);
//resultado en consola : 
(3) ['manzana', 'banana', 'naranja']


// resultado en consola del ejercicio :
Error en la ejecución del código: buscaPalabras is not defined
