### ISSUE TITLE
Enunciado no corresponde con solución.

### ISSUE THREAD

**Issue by ghost** [midudev/aprende-javascript-problemas#343]
¡Hola!
En el tema Operadores lógicos en JavaScript el ejercicio:

Tenemos un producto en una tienda. Cuesta 1500 y tenemos un descuento del 25%. Tengo 1150€ en mi cartera. Escribe un código que me diga si puedo comprarlo. No uses paréntesis.

La solución propuesta es:

1500 * 0.75 <= 1150

Cuando debería ser:

1500 * 0.25 <= 1150

¡Me estaba volviendo loco ya que no quería mirar la solución y no sabía qué pasaba! 

Gracias por el currazo y todo lo que haces, Midu.

Un saludo.

**Comment by osrecio** [comment]
1500 * 0.75 = 1125€ que es el valor del producto con descuento.
1500 * 0.25 = 375€ que es el descuento.

Por lo tanto si yo tengo 1150€ en mi cartera puedo comprar un producto que valga 1125€ con descuento.

Por lo tanto la solución sugerida es correcta

**Comment by ghost** [comment]
Ahhh, jolín es verdad ¡seré zopenco!
