### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by jostus93** [midudev/aprende-javascript-problemas#351]
No puedo reproducir ningún video explicativo ni desde safari ni en brave. Estos son los errores que salen en la consola.

 [Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-opt.mp4, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-2-opt.mp4, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-opt.vtt, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-2-opt.vtt, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-opt.mp4, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-2-opt.mp4, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-opt.vtt, line 0)
[Error] Failed to load resource: No se ha encontrado ningún servidor con el nombre de host especificado. (bucle-2-opt.vtt, line 0)

**Comment by oconner999** [comment]
No puedo reproducir ningún video explicativo ni desde safari ni en brave. Estos son los errores que salen en la consola.
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/intro-js-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/intro-js-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
background.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'onCompleted')
    at window.onload (background.js:5:23)
video.aprendejs.dev/intro-js-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
39Error in event handler: TypeError: window.bg[obj.method] is not a function
    at methodCaller (<URL>)
video.aprendejs.dev/intro-js-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/intro-js-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/intro-js-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/intro-js-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/consola-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/consola-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/consola-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/consola-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/tipos-de-datos-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/tipos-de-datos-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/tipos-de-datos-opt.mp4:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
video.aprendejs.dev/tipos-de-datos-opt.vtt:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
