### ISSUE TITLE
Ejercicio interactivo seccion Arrays

### ISSUE THREAD

**Issue by ianaut** [midudev/aprende-javascript-problemas#368]
Buenas!

En el examen de la sección de arrays tenemos el siguiente código:

const numbers = [1, 2, 3, 4, 5]
numbers[0] = 10
numbers[2] = 30
console.log(numbers)

Y las respuestas posibles son las siguientes

-[1, 2, 3, 4, 5]
-[10, 2, 30, 4, 5]
-Error de asignación a una constante

El resultado correcto es el segundo pero el 30 debería estar en la tercera posición,

Siento si es un reporte duplicado pero no he encontrado otro post con este error.

Al menos este tiene facil solución :D

**Comment by MFrutuoso** [comment]
> Buenas!
> 
> En el examen de la sección de arrays tenemos el siguiente código:
> 
> const numbers = [1, 2, 3, 4, 5] numbers[0] = 10 numbers[2] = 30 console.log(numbers)
> 
> Y las respuestas posibles son las siguientes
> 
> -[1, 2, 3, 4, 5] -[10, 2, 30, 4, 5] -Error de asignación a una constante
> 
> El resultado correcto es el segundo pero el 30 debería estar en la tercera posición,
> 
> Siento si es un reporte duplicado pero no he encontrado otro post con este error.
> 
> Al menos este tiene facil solución :D

Hola @ianaut ,

Los arrays comienzan en la posición 0, por lo que el número 30 se encuentra correctamente, quedaría:
**-[10, 2, 30, 4, 5]**
numbers[0] = 10,
numbers[1] = 2,
numbers[2] = 30,
numbers[3] = 4,
numbers[4] = 5

Si crees que esta respuesta ha sido útil, puedes cerrar la issue.

Un saludo
