### ISSUE TITLE
Cant Sign In

### ISSUE THREAD

**Issue by Azraeth** [midudev/aprende-javascript-problemas#372]
No se puede iniciar sesión, al hacerlo en vez de ejecutar el script me manda a un enlace inválido en vez de verificar las credenciales.

![image](https://github.com/midudev/aprende-javascript-problemas/assets/51485701/e9dfa706-520f-4866-95a0-0046131c7702)

![imagen_2024-01-11_044409071](https://github.com/midudev/aprende-javascript-problemas/assets/51485701/e0ee7df1-6029-4edf-ae8c-d53f47d5aac8)

**Comment by midudev** [comment]
Ya debería estar arreglado
