### ISSUE TITLE
Volver a la página principal desde una clase

### ISSUE THREAD

**Issue by pmuller2010** [midudev/aprende-javascript-problemas#38]
Después de cada lección se puede ir a la siguiente lección pero no a la pantalla principal para ver los progresos o siguientes lecciones.

**Comment by creativoma** [comment]
Esto estaba viendo.

Ahora:
![image](https://user-images.githubusercontent.com/66380259/233436373-22b984ad-86aa-4096-abe2-86b9c2db02f8.png)

Propuesta:

![image](https://user-images.githubusercontent.com/66380259/233437053-fd5e02a6-b188-4081-b1f5-5cf1cbec6b56.png)

**Comment by pmuller2010** [comment]
Recién veo que se puede con el icono que esta arriba a la izquierda, no me parece intuitivo, ya que al estar el botón para ir a la siguiente lección me parece que también tendría que estar ahí el de volver a la principal.

**Comment by midudev** [comment]
Hemos añadido un botón para volver atrás:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1561955/233623685-27ffff22-52ff-4634-abac-581f355b3102.png">
