### ISSUE TITLE
Error bienvenida con google

### ISSUE THREAD

**Issue by LucianoOPM** [midudev/aprende-javascript-problemas#39]
Cuando te logueas con google el mensaje de bienvenida de la página aparece incompleto. "Bienvenido, "
![imagen_2023-04-20_110100782](https://user-images.githubusercontent.com/113417117/233436934-ee8a84a6-a26c-4b8b-abb6-beb2872c2c04.png)

**Comment by midudev** [comment]
¡Ya está arreglado!
