### ISSUE TITLE
Error en el porcentaje

### ISSUE THREAD

**Issue by Soyalguien2324** [midudev/aprende-javascript-problemas#394]
En este texto hay un error. Dice descuento del 25%, pero si le das a ver solución el descuento el del 75%
```
Tenemos un producto en una tienda. Cuesta 1500 y tenemos un descuento del 25%. Tengo 1150€ en mi cartera. Escribe un código que me diga si puedo comprarlo. No uses paréntesis.
1500 * 0.75 <= 1150
```

**Comment by iromero1102** [comment]
> En este texto hay un error. Dice descuento del 25%, pero si le das a ver solución el descuento el del 75%
> 
> ```
> Tenemos un producto en una tienda. Cuesta 1500 y tenemos un descuento del 25%. Tengo 1150€ en mi cartera. Escribe un código que me diga si puedo comprarlo. No uses paréntesis.
> 1500 * 0.75 <= 1150
> ```

No es un error, la respuesta correcta utiliza 0.75 porque de esa manera estaría calculando cual es el 75% del valor total, lo que es equivalente a restarle 25% que corresponde al descuento.
