### ISSUE TITLE
Clases en progreso no desbloqueadas

### ISSUE THREAD

**Issue by zenix-s** [midudev/aprende-javascript-problemas#43]
Si te usas uno de los links de una clase que todavía no esta desbloqueada se te pone en progreso
![imagen](https://user-images.githubusercontent.com/80365583/233437432-87a3ade1-c7e2-4352-9739-d3d03c8b7c54.png)

**Comment by midudev** [comment]
Arreglado, para evitar que la gente pueda entrar a una clase que no está abierta.
