### ISSUE TITLE
Da por incorrectas algunas soluciones por los espacios

### ISSUE THREAD

**Issue by matiasbaldanza** [midudev/aprende-javascript-problemas#48]
En [este desafío de operadores de comparación]:(https://www.aprendejavascript.dev/clase/introduccion/operadores-de-comparacion)

Si cargo la expresión sin un espacio después del operador, da INCORRECTO! (En VS Code o en cualquier Consola o RunJS funciona)
![Screen Shot 2023-04-20 at 14 05 23](https://user-images.githubusercontent.com/55600/233438057-f0bd17b0-55b6-4ef2-b0e5-7b804efc6a35.png)

Si agrego el espacio, da correcto.
![Screen Shot 2023-04-20 at 14 05 43](https://user-images.githubusercontent.com/55600/233438350-4381ede5-29c7-4aa5-b2b2-4551e98f84ec.png)

Será que el test compara strings en lugar de ejecutar la expresión? 

Creo que es bueno que los tests sean tan permisivos o estrictos como un entorno de ejecución real.

Saludos! ✌️😁

**Comment by midudev** [comment]
Arreglado.
