### ISSUE TITLE
El logo en mobile hace un poco de ruido por el opacity

### ISSUE THREAD

**Issue by JJRR5** [midudev/aprende-javascript-problemas#5]
![image](https://user-images.githubusercontent.com/76703666/233425618-592693d7-4572-4418-8eb3-772c71266b44.png)

![image](https://user-images.githubusercontent.com/76703666/233425971-9ee03e8e-18ef-4627-90e1-1fcf3b9cae55.png)

**Posible solucion**
Cambiar el opacity o el color para que se vea menos transparente

**Comment by midudev** [comment]
Ya no debería verse el logo.
