### ISSUE TITLE
Aparece código HTML en una de las respuestas de una pregunta

### ISSUE THREAD

**Issue by Jaffilorex** [midudev/aprende-javascript-problemas#54]
En una de las respuestas de la última pregunta del apartado de variables de la Introducción, aparece código HTML. Adjunto captura para que se entienda mejor

![image](https://user-images.githubusercontent.com/73447711/233439816-e653ce11-30b3-41db-bd91-f99277dbd038.png)

**Comment by midudev** [comment]
Arreglado.
