### ISSUE TITLE
Inicio de sesión con google

### ISSUE THREAD

**Issue by jonathanmaster** [midudev/aprende-javascript-problemas#55]
Inicie sesión con GitHub y me llego el correo, después entre con Google y todo normal hasta que me aparece el nombre de GitHub y el avatar. No se que pasaría ahí

**Comment by JeronimoOG** [comment]
Me  pasa lo mismo, aunque no me muestra la imagen

**Comment by midudev** [comment]
Es normal. Eso es porque has iniciado sesión con Google y GitHub, en las dos cuentas usas el mismo email y lo que hace es fusionar la cuenta.
