### ISSUE TITLE
Ejercícios de codigo interactivo - Evaluación de respuesta correcta vs incorrecta

### ISSUE THREAD

**Issue by emedeiros** [midudev/aprende-javascript-problemas#56]
En el 1º ejercício sobre Operadores lógicos en JavaScript, la respuesta que había introducido era correcta, pero me saló el resultado como respuesta incorrecta. 
Esto ocurrió por no haber añadido un espacio entre el operador lógico y el número. 

<img width="762" alt="Screenshot 2023-04-20 at 18 10 10" src="https://user-images.githubusercontent.com/6769242/233439338-99130715-4351-4720-81c6-342410858b9a.png">

<img width="789" alt="Screenshot 2023-04-20 at 18 10 24" src="https://user-images.githubusercontent.com/6769242/233439344-592c1c55-daa3-4cad-b61b-986944bdc7b4.png">

Saludos

**Comment by midudev** [comment]
Repetido: https://github.com/midudev/aprende-javascript-problemas/issues/48
