### ISSUE TITLE
En ejercicios "Operadores de comparación" no soporta otras formas de escribir 

### ISSUE THREAD

**Issue by soyluisarrieta** [midudev/aprende-javascript-problemas#57]
1. Esto debería ser correcto:
![image](https://user-images.githubusercontent.com/88900534/233439153-75b5aeed-7c8f-46bd-9d95-0aa9aa3ba783.png)

2. Esto debería ser correcto:
![image](https://user-images.githubusercontent.com/88900534/233439396-8e36cde5-8850-4ccd-bbe0-6ab92f4f78d7.png)

3. Esto debería ser correcto:
![image](https://user-images.githubusercontent.com/88900534/233439535-b8137523-5e96-4873-9ef8-c4ee7eb4ceda.png)

**Comment by soyluisarrieta** [comment]
También sucede en los demás ejercicios interactivos:
![image](https://user-images.githubusercontent.com/88900534/233447933-38d66ad1-de8f-4273-8140-5a7587313b0c.png)

**Comment by midudev** [comment]
Repetido: https://github.com/midudev/aprende-javascript-problemas/issues/48
