### ISSUE TITLE
When I put see solution in the interactive questions it does not matter if the answer is correct or not always marks me as correct answer and should not

### ISSUE THREAD

**Issue by luismacode** [midudev/aprende-javascript-problemas#59]
![Screenshot 2023-04-20 122050](https://user-images.githubusercontent.com/88962832/233441528-4febee38-808e-4f80-8bcf-155d64b00878.png)

**Comment by midudev** [comment]
Related: https://github.com/midudev/aprende-javascript-problemas/issues/25
