### ISSUE TITLE
Problema en operadores de comparación

### ISSUE THREAD

**Issue by LucianoOPM** [midudev/aprende-javascript-problemas#61]
Si el código lo coloco sin espacios, me toma el desafio como respuesta incorrecta 
![imagen_2023-04-20_112229056](https://user-images.githubusercontent.com/113417117/233441543-839ae087-b922-49a0-8616-d616a55df2c9.png)
Y dentro de la consola me salen dos console.log como undefined
![imagen_2023-04-20_112341260](https://user-images.githubusercontent.com/113417117/233441797-2959be2d-e4a2-414e-9ba3-32bd09fdb88f.png)

**Comment by xechezurieta-cafds** [comment]
Ocurre lo mismo también en el caso de los operadores lógicos
![image](https://user-images.githubusercontent.com/87265438/233450025-900f4a51-2b3e-48d5-8b3e-dae608026556.png)

**Comment by midudev** [comment]
Repetido: https://github.com/midudev/aprende-javascript-problemas/issues/48
