### ISSUE TITLE
Fallo texto en https://www.aprendejavascript.dev/clase/introduccion/variables 

### ISSUE THREAD

**Issue by joseluisbugallo** [midudev/aprende-javascript-problemas#62]
En el Examen de https://www.aprendejavascript.dev/clase/introduccion/variables
La tercera respuesta no esta interpretando la etiqueta code
![image](https://user-images.githubusercontent.com/9093998/233441830-508bb4ca-74c5-4405-9f81-07d19e224578.png)

**Comment by midudev** [comment]
Fixed!
