### ISSUE TITLE
No se puede volver al inicio

### ISSUE THREAD

**Issue by msalmon-l** [midudev/aprende-javascript-problemas#63]
Desde la versión del móvil, una vez accedes dentro de un punto ya no aparece la opción de ir al inicio.

**Comment by midudev** [comment]
Hemos mejorado la versión móvil.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1561955/233622708-84dbb36a-5669-47d2-9cf6-af0194f23126.png">
