### ISSUE TITLE
En los ejercicios interactivos no sobrescribe al solicitar la solución

### ISSUE THREAD

**Issue by soyluisarrieta** [midudev/aprende-javascript-problemas#67]
Suponiendo que el usuario realizó algunos intentos y desea ver la solución, al principio sobrescribe pero las siguientes veces no lo hace:
![image](https://user-images.githubusercontent.com/88900534/233443686-e944289a-6b54-44b5-bbb7-dde4ebf37414.png)

**Comment by midudev** [comment]
Repetida en:
https://github.com/midudev/aprende-javascript-problemas/issues/25
