### ISSUE TITLE
Añadir botón Volver a clase anterior

### ISSUE THREAD

**Issue by armarian** [midudev/aprende-javascript-problemas#69]
crees que sería posible añadir un botón de clase anterior? El clase siguiente está y es perfecto, pero no sé si sería bueno incluir un botón de clase anterior.
Gracias por tu supercurso!!

**Comment by midudev** [comment]
He añadido una navegación inferior:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1561955/233623245-125f072d-8b7d-4bb3-883a-85c9a4b2b90c.png">
