### ISSUE TITLE
Falso "Nuevo logro desbloqueado"

### ISSUE THREAD

**Issue by dantedenicolo** [midudev/aprende-javascript-problemas#72]
Cada vez que se completa una clase sale la alerta de "Nuevo logro desbloqueado" pero no siempre ocurre esto (solo hay 3 logros disponibles hasta el momento y 9 clases en las que aparece la alerta).

**Comment by midudev** [comment]
No he sido capaz de replicarlo. ¿Te pasa cada vez que finalizas un examen?

**Comment by midudev** [comment]
Creo que ya está arreglado. :)

**Comment by dantedenicolo** [comment]
> Creo que ya está arreglado. :)

Genial midu!
