### ISSUE TITLE
Inicie sesion con mi correo y me sale el nombre de mi GitHub

### ISSUE THREAD

**Issue by JeronimoOG** [midudev/aprende-javascript-problemas#78]
Ese es el problema en si, cree primero una cuenta de github pero como no funcionaba intente entrar con google, funciono pero me sale el nombre de github

**Comment by midudev** [comment]
Eso es porque has iniciado con las dos cuentas, que comparten email, y lo que hace supabase es mergear el usuario.

**Comment by silcava** [comment]
Yo tambien he iniciado con las dos cuentas, tambien comparto email, y con cada una me sale un nombre. En cambio mi novia que tambien es el mismo mail le sale el de github y nunca el de google.

**Comment by JMDTol** [comment]
Seguro?
![image](https://user-images.githubusercontent.com/53052609/233502565-3ebd285c-d1d0-4ade-88d5-cf8734308432.png)
![image](https://user-images.githubusercontent.com/53052609/233502164-64b12887-0678-4cc9-9e93-10e83cc4f5a3.png)
![image](https://user-images.githubusercontent.com/53052609/233502253-6129cd25-38dc-4eba-ba80-fad8cffecece.png)
![image](https://user-images.githubusercontent.com/53052609/233502363-033d876a-d5d4-45fe-9678-d8afc5d50b9a.png)
