### ISSUE TITLE
Error en ejercicio interactivo de Operadores lógicos en JavaScript

### ISSUE THREAD

**Issue by JowiiProgramming** [midudev/aprende-javascript-problemas#79]
![image](https://user-images.githubusercontent.com/70163681/233444802-dbed5583-640b-494c-9557-a4c864776ccd.png)

Quizá estoy yo tonto pero si es el 25% deberia ser por 0.25 y no por 0.75 no ?

**Comment by xechezurieta-cafds** [comment]
No, el 25% es el descuento, no lo que te cuesta.
Por ejemplo: si vale 100€ y tienes un 25% de descuento el descuento es 100*0.25 = 25 euros, pero el dinero que tu tienes que tener para comprarlo es 100*0.75=75

**Comment by JowiiProgramming** [comment]
Pues soy tonto no lo veo de donde sacas 75. Porque tu tienes 1150 euros hasta ahí OK.
Vale ahora el producto cuesta 1500 pero a eso hay que restarle el 25 % de descuento que tenemos. Nos quedaria que debemos pagar por el producto 1125 euros. 

Lo que anterior comentaba yo tampoco seria correcto. Pero lo que ahora comento seria para hacerlo con parentesis porque habria que hacer una multiplicación y luego restar. Pero si hay que hacerlo sin parentesis con la explicación que me has dado no te comprendo de donde sale 75

**Comment by FernandoCM18** [comment]
Puedes hacerlo asi 1500 >= 1500 - 1500 * 0.25 y seria correcto tambien, solo que te lo marca como incorrecto en el ejercicio pero en consola si te da true.
Y el porque pone 75% es porque en vez de poner esto 1500 - 1500 * 0.25 lo que se hizo en el ejercicio para simplificarlo y no hacer la resta es al 100% restarle el 25% de descuento y eso directamente te dara el valor y evitas el hacer la operación de la resta.

**Comment by JowiiProgramming** [comment]
Vale de acuerdo. Muchas gracias a veces soy un poco corto de mente tienes razón asi simplificas el código.
