### ISSUE TITLE
En Movil, el botón de compartir en twitter queda estorbando en la pantalla

### ISSUE THREAD

**Issue by Ameth** [midudev/aprende-javascript-problemas#80]
El boton de twitter queda en medio del texto cuando se ve en movil.

![Imagen de WhatsApp 2023-04-20 a las 12 44 24](https://user-images.githubusercontent.com/1568292/233446311-1a259e05-d25c-45b4-915f-a963ccb01022.jpg)

**Comment by midudev** [comment]
Hemos mejorado la navegación en móvil y ya no molesta.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1561955/233624249-03982763-1010-4ae0-b518-ff427677749d.png">
