### ISSUE TITLE
Sección de las variables a la hora de escribir se ve el autocompletado lejos

### ISSUE THREAD

**Issue by jonathanmaster** [midudev/aprende-javascript-problemas#85]
![image](https://user-images.githubusercontent.com/89710954/233448139-e044fdc4-1add-4216-aa46-e6ba13eedc1e.png)

**Comment by jonathanmaster** [comment]
![image](https://user-images.githubusercontent.com/89710954/233448422-e77f3448-7cfc-4a23-a7f0-d2de8e8ff736.png)

**Comment by midudev** [comment]
Arreglado. Lo he desactivado. :)
