### ISSUE TITLE
tikismikis

### ISSUE THREAD

**Issue by futMikelDev** [midudev/aprende-javascript-problemas#86]
**En la lección de las variables, se asigna el valor 1 a la variable 'numero', pero después, al agregar 'numero + 1', el output es '0 + 1'  y debería ser '1 + 1'**:

Tenemos una variable llamada numero pero no le hemos asignado ningún valor. Para asignarle un valor, usamos el operador de asignación =:
_let numero = 1_

Ahora, podemos referirnos a la variable numero y obtener el valor que le hemos asignado.
_numero + 1 // -> 0 + 1_

**Comment by midudev** [comment]
Fixed!
