### ISSUE TITLE
Modulo: Introduccion - Operador typeof - Pregunta 2 repetida.

### ISSUE THREAD

**Issue by DoroteoNavarrete** [midudev/aprende-javascript-problemas#87]
Hola midu, primero GRACIAS por tanto, segundo te reporto algo que note y me parece que no va ahi.

Esta es la seg pregunta del examen en null y indefined : https://prnt.sc/wOVd7fS4-hEj

Pero si miras en el examen de Operador typeOf notaras que esta repetida y no creo que sea la que quisiste poner.

**Comment by midudev** [comment]
Fixed.
