### ISSUE TITLE
Operadores de comparación - Sustitución extraña

### ISSUE THREAD

**Issue by alejandro-dc** [midudev/aprende-javascript-problemas#89]
Cuando ingresé 10 >= 9 hizo un reemplazo por un símbolo mayor o igual.
Lo mismo ocurrió cuando ingresé === 
![image](https://user-images.githubusercontent.com/375596/233448792-8667491e-5fce-447b-864b-ebfd53069053.png)

**Comment by soyluisarrieta** [comment]
Es normal, es una fuente tipográfica y a este tipo de "sustituciones" se le conoce como ligaduras. Aquí un video de Midudev hablando sobre esto:

[![image](https://user-images.githubusercontent.com/88900534/233452483-5dc5ecd5-eaff-4c12-a564-5e767550a6bd.png)](https://www.youtube.com/watch?v=yKDVMquVIMI)
**[Ver en YouTube](https://www.youtube.com/watch?v=yKDVMquVIMI)**

**Comment by alejandro-dc** [comment]
Hola Luis, muchas gracias por responder. 
Muy bueno el video de midu sobre ligaduras.
