### ISSUE TITLE
Error visual modulo null y undefined

### ISSUE THREAD

**Issue by Alb3G** [midudev/aprende-javascript-problemas#92]
Al escribir las soluciones sale una caja a la derecha como de auto completado o de palabra reservada adjunto screenshot
![Captura de pantalla 2023-04-20 a las 20 01 53](https://user-images.githubusercontent.com/115070855/233450820-c025b564-cdb9-4683-b45a-7afbf72b0264.png)

**Comment by midudev** [comment]
Ya está desactivado el autocomplete y no debería volver a salir.
