### ISSUE TITLE
Correct answer not accepted without spaces

### ISSUE THREAD

**Issue by Sylphadora** [midudev/aprende-javascript-problemas#93]
The answer is the same in both cases but if it is written with no spaces, it is marked as wrong: 

![Screenshot from 2023-04-20 20-03-32](https://user-images.githubusercontent.com/131396380/233450567-e9139b29-5a22-4deb-8f8b-5af04aa67061.png)

![Screenshot from 2023-04-20 20-04-57](https://user-images.githubusercontent.com/131396380/233450773-61743294-0148-467b-bf18-013037b79e2c.png)

**Comment by cjodra** [comment]
En este otro caso sucede lo mismo:
![ko](https://user-images.githubusercontent.com/58395291/233492962-85a856e1-efa8-4907-8105-89ee0a441e85.JPG)
![ok](https://user-images.githubusercontent.com/58395291/233492976-ab23cdf7-ab3f-44f4-8976-18b8c544865b.JPG)

**Comment by midudev** [comment]
Repe: https://github.com/midudev/aprende-javascript-problemas/issues/48
