### ISSUE TITLE
No valida si no coinciden los espacios.

### ISSUE THREAD

**Issue by PeHachePe** [midudev/aprende-javascript-problemas#96]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/37072199/233452257-495af71d-2c5a-4c3f-9e32-c4e1404af086.png">

**Comment by PeHachePe** [comment]
![Uploading image.png…]()

**Comment by PeHachePe** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/37072199/233452616-7fd7e555-1643-43ea-85d0-5047d6a39e89.png">

**Comment by midudev** [comment]
Repetido: https://github.com/midudev/aprende-javascript-problemas/issues/48
