### ISSUE TITLE
Error validar

### ISSUE THREAD

**Issue by PeHachePe** [midudev/aprende-javascript-problemas#97]
Realmente no valida que la solución sea valida sino que pongas exactamente la que se espera, si lo haces de otra forma con mismo resultado da error.
Por otro lado una vez le das a ver solución, si luego borras y le das de nuevo a ver solución, deja de funcionar y des al botón que des dice que es valida la respuesta a pesar de estar en blanco.
<img width="777" alt="image" src="https://user-images.githubusercontent.com/37072199/233453995-259b9074-4dae-44f5-a9bb-cca894bc5d37.png">

**Comment by midudev** [comment]
Repe: https://github.com/midudev/aprende-javascript-problemas/issues/96
