### ISSUE TITLE
Operador typeof

### ISSUE THREAD

**Issue by O-Sergio274** [midudev/aprende-javascript-problemas#98]
typeof dogId === string

lo marca como respuesta incorrecta.

**Comment by Alejandro-CP** [comment]
Porque lo que te devuelve el `typeof` es una cadena de caracteres y el resultado de `typeof dogId` lo estás comparando con lo que vendría a ser una función llamada string y no una cadena de caracteres.
Prueba usando la consola de las  dev tools del navegador y verás facilmente el error y como solucionarlo, porque incluso a mí mi explicación me parece poco clara XDXD
